// ═══════════════════════════════════════════════════════════════════
// projects_data.js  —  Complete Project Portfolio Data
// ═══════════════════════════════════════════════════════════════════

window.CLUSTERS = [
  { id: 'vision', label: 'AI & CV', full: 'AI & Computer Vision', color: 0x3b82f6, css: '#3b82f6', emoji: '👁️' },
  { id: 'robotics', label: 'ROBOTICS', full: 'Robotics & Autonomous Systems', color: 0x06b6d4, css: '#06b6d4', emoji: '🤖' },
  { id: 'embedded', label: 'EMBEDDED', full: 'Embedded & Hardware', color: 0xf97316, css: '#f97316', emoji: '🔌' },
  { id: 'software', label: 'SOFTWARE', full: 'Desktop Applications', color: 0x10b981, css: '#10b981', emoji: '💻' },
  { id: 'mobile', label: 'MOBILE & AR', full: 'Mobile & Augmented Reality', color: 0x8b5cf6, css: '#8b5cf6', emoji: '📱' },
  { id: 'games', label: 'GAMES', full: 'Games & Interactive', color: 0xd946ef, css: '#d946ef', emoji: '🎮' },
  { id: 'research', label: 'RESEARCH', full: 'Research & Dev Tools', color: 0xec4899, css: '#ec4899', emoji: '🔬' },
  { id: 'others', label: 'OTHERS', full: 'Miscellaneous & Sandbox', color: 0x64748b, css: '#64748b', emoji: '📂' },
];

window.PINNED_PROJECTS = [
  'autoseg',
  'jarviscontrolsystem',
  'lanemappingtool',
  'adas-for-indian-road-vehicle',
  'facerecognition',
  'mbd-dspace',
  'droid-slam',
];

window.PROJECTS = [

  // ── AI & COMPUTER VISION ────────────────────────────────────────────────────────────────
{
    id: 'adas_for_indian_road_vehicle',
    cluster: 'vision',
    name: 'ADAS-for-Indian-Road-Vehicle',
    lang: 'Python',
    tagline: 'ADAS system tailored for Indian road conditions using YOLOv8-Seg',
    summary: 'Advanced Driver Assistance Systems (ADAS) tailored for Indian road conditions. This project focuses on road segmentation, object detection, and instance segmentation using the YOLOv8-Seg model. Features a diverse dataset of 45,000+ annotated images and utilizes superpixel segmentation to enhance accuracy.',
    highlights: [
      'YOLOv8-Seg for instance segmentation',
      'Road segmentation and object detection',
      'Trained on diverse dataset of Indian roads (45,000+ images)',
      'Superpixel Segmentation (SLIC)'
    ],
    tech: ['Python', 'YOLOv8', 'Computer Vision', 'PyTorch', 'SAM2'],
    github: 'https://github.com/thippeswammy/ADAS-for-Indian-Road-Vehicle',
    demo: '',
    docs: '',
    paper: '',
    isPrivate: false,
    status: 'completed',
    year: '',
    team: 'solo',
    platform: [],
    datasets: [],
    thumbnail: '',
    images: [],
    metrics: {
      iou: '0.8983',
      precision: '0.9692',
      recall: '0.9501',
      accuracy: '95.21%'
    }
  },

{
    id: 'autoseg',
    cluster: 'vision',
    name: 'AutoSegmentor',
    lang: 'Python',
    tagline: 'State-of-the-art AI auto-labeling and segmentation dataset creation suite',
    summary: 'An end-to-end AI-powered auto-labeling and segmentation ecosystem. Integrates Meta AI\'s Segment Anything Model 2 (SAM2) and CoTracker keypoint tracking within a responsive PyQt5 multi-window desktop interface. It propagates frame annotations over complex video files to create pixel-perfect masks, which are then compiled into fully augmented, YOLOv8/v11-compatible object detection and instance segmentation datasets.',
    highlights: [
      'Meta SAM2 integration for real-time temporal mask propagation across video sequences',
      'CoTracker and Lucas-Kanade trackers for high-accuracy keypoint and optical flow tracking',
      'Fully featured PyQt5 interactive canvas with precise foreground/background points, zoom, and undo/redo systems',
      'Multi-threaded, asynchronous background ML inference to maintain GUI responsiveness',
      'Seamless YOLO format dataset exporter with integrated copy-paste and visual data augmentations'
    ],
    tech: ['Python', 'PyQt5', 'PyTorch', 'SAM2', 'CoTracker', 'CUDA', 'YOLOv8', 'OpenCV'],
    github: 'https://github.com/thippeswammy/AutoSegmentor',
    demo: 'https://drive.google.com/file/d/1Y19lwf_IIuzwVe-3j9vX0uicV_iWbrHZ/view?usp=sharing',
    docs: 'script/AutoSegmentor/README.md',
    paper: '',
    isPrivate: false,
    status: 'completed',
    year: '2026',
    team: 'solo',
    platform: ['Windows', 'Linux', 'CUDA'],
    datasets: ['Custom Videos'],
    thumbnail: '',
    images: ['assets/AutoSegmenter_1080.gif'],
    metrics: {}
  },

{
    id: 'facerecognition',
    cluster: 'vision',
    name: 'FaceRecognition',
    lang: 'Python',
    tagline: 'Versatile Face Recognition System with Auto-Tagging and YOLO Classification',
    summary: 'A versatile Face Recognition System featuring two distinct subsystems for different use cases: Dynamic Auto-Tagging (One-Shot Learning) using Intel RealSense for depth sensing, and Static YOLO Classification (Supervised Training) for high-accuracy face classification via traditional neural network training.',
    highlights: [
      'Dynamic Auto-Tagging with One-Shot learning',
      'Intel RealSense Depth filtering and Kalman Filter tracking',
      'Static YOLOv8 Classification with custom dataset training',
      'Raspberry Pi integration for physical access control',
      'Text-to-Speech (TTS) feedback'
    ],
    tech: ['Python', 'OpenCV', 'YOLOv8', 'face_recognition', 'dlib', 'Intel RealSense SDK', 'PyTorch'],
    github: 'https://github.com/thippeswammy/FaceRecognition',
    demo: '',
    docs: '',
    paper: '',
    isPrivate: false,
    status: 'completed',
    year: '',
    team: 'solo',
    platform: ['Windows', 'Linux', 'Raspberry Pi'],
    datasets: [],
    thumbnail: '',
    images: [],
    metrics: {}
  },

{
    id: 'imageprocessingcourse',
    cluster: 'vision',
    name: 'ImageProcessingCourse',
    lang: '',
    tagline: 'Image Processing Course',
    summary: 'Repository for an Image Processing Course.',
    highlights: [],
    tech: ['Image Processing'],
    github: 'https://github.com/thippeswammy/ImageProcessingCourse',
    demo: '',
    docs: '',
    paper: '',
    isPrivate: false,
    status: 'completed',
    year: '',
    team: 'solo',
    platform: [],
    datasets: [],
    thumbnail: '',
    images: [],
    metrics: {}
  },

{
    id: 'lanelinesdetection',
    cluster: 'vision',
    name: 'LaneLinesDetection',
    lang: 'Python',
    tagline: 'Advanced road and lane line detection suite using traditional CV & Deep Learning',
    summary: 'A state-of-the-art comparative suite evaluating traditional CV algorithms and deep learning models for road and lane line tracking. Features sliding windows, perspective transforms, U-Net semantic segmentation, and a flagship real-time GPU-accelerated HybridNets ONNX pipeline running at 60+ FPS with sensor fusion overlays.',
    highlights: [
      'Flagship ONNX HybridNets pipeline executing at 60+ FPS using CUDA acceleration',
      'U-Net semantic segmentation trained on a custom South Indian road dataset',
      'Udacity advanced lane finding with camera calibration and sliding windows',
      'Real-time 4-quadrant sensor fusion visual dashboard with IoU validation'
    ],
    tech: ['Python', 'OpenCV', 'ONNX Runtime', 'CUDA', 'TensorFlow', 'PyTorch'],
    github: 'https://github.com/thippeswammy/LaneLinesDetection',
    demo: '',
    docs: '',
    paper: 'https://arxiv.org/abs/2203.09035',
    isPrivate: false,
    status: 'completed',
    year: '',
    team: 'solo',
    platform: ['Linux', 'CUDA'],
    datasets: ['Custom South Indian Roads'],
    thumbnail: '',
    images: ['showcase_gifs/Detected15.gif', 'showcase_gifs/all2.gif'],
    metrics: {}
  },

{
    id: 'zed2i',
    cluster: 'vision',
    name: 'ZED2i',
    lang: 'Python',
    tagline: 'Advanced Stereo Vision Pipeline & Synchronized Multi-Camera Acquisition',
    summary: 'A professional-grade ecosystem for StereoLabs ZED2i and Intel RealSense D435i integration. It bridges the gap between raw spatial data acquisition and high-level AI perception, featuring deep learning-based depth estimation using stereo pairs and synchronized multi-camera recording.',
    highlights: [
      'Synchronized multi-camera recording (ZED + RealSense)',
      'Deep learning-based depth estimation (Mask R-CNN ResNet50)',
      'Hungarian Matching and CM-Level Depth',
      'High-Freq IMU Logging'
    ],
    tech: ['Python', 'ZED SDK', 'Intel RealSense SDK', 'PyTorch', 'OpenCV'],
    github: 'https://github.com/thippeswammy/ZED2i',
    demo: '',
    docs: '',
    paper: '',
    isPrivate: false,
    status: 'completed',
    year: '',
    team: 'solo',
    platform: [],
    datasets: [],
    thumbnail: '',
    images: [],
    metrics: {}
  },


  // ── ROBOTICS & AUTONOMOUS SYSTEMS ────────────────────────────────────────────────────────────────
{
    id: '3d_robot',
    cluster: 'robotics',
    name: '3d_robot',
    lang: 'C++',
    tagline: '3D Vehicle Navigation and SLAM',
    summary: 'Provides tools for 3D SLAM, terrain analysis, and autonomous navigation for vehicles in uneven environments using ROS 2 and Gazebo. Features data collection (Mapping Flow), post-processing Map Generation from rosbag, and Autonomous Navigation with PCD maps.',
    highlights: [
      '3D SLAM and terrain analysis',
      'Autonomous navigation for vehicles in uneven environments',
      'ROS 2 and Gazebo integration'
    ],
    tech: ['C++', 'ROS 2', 'Gazebo', 'SLAM', 'PCD'],
    github: 'https://github.com/thippeswammy/3d_robot',
    demo: '',
    docs: '',
    paper: '',
    isPrivate: false,
    status: 'completed',
    year: '',
    team: 'solo',
    platform: ['ROS 2'],
    datasets: [],
    thumbnail: '',
    images: [],
    metrics: {}
  },

{
    id: 'carla',
    cluster: 'robotics',
    name: 'Carla',
    lang: 'Python',
    tagline: 'CARLA simulator Python API workspace',
    summary: 'A workspace containing scripts utilizing the CARLA Python API used for controlling and communicating with the open-source CARLA simulator for autonomous driving research. Includes functionality for controlling simulation actors and retrieving sensor data.',
    highlights: [
      'Controls the CARLA simulator',
      'Retrieves simulation data through the Python API'
    ],
    tech: ['Python', 'CARLA'],
    github: 'https://github.com/thippeswammy/Carla',
    demo: '',
    docs: '',
    paper: '',
    isPrivate: false,
    status: 'completed',
    year: '',
    team: 'solo',
    platform: [],
    datasets: [],
    thumbnail: '',
    images: [],
    metrics: {}
  },

{
    id: 'dpvo',
    cluster: 'robotics',
    name: 'DPVO',
    lang: 'Python',
    tagline: 'Deep Patch Visual Odometry / SLAM',
    summary: 'Source code for Deep Patch Visual Odometry and Deep Patch Visual SLAM. A deep learning-based visual odometry and SLAM system that estimates trajectories and dense point clouds from monocular video sequences. Includes integration with Pangolin Viewer and a classical loop closure backend.',
    highlights: [
      'Deep Patch Visual Odometry (DPVO)',
      'Deep Patch Visual SLAM (DPV-SLAM) with loop closure',
      'Pangolin Viewer for real-time visualization',
      'Evaluated on TartanAir, EuRoC, TUM-RGBD, ICL-NUIM, and KITTI'
    ],
    tech: ['Python', 'PyTorch', 'CUDA', 'C++', 'Pangolin', 'SLAM'],
    github: 'https://github.com/thippeswammy/DPVO',
    demo: '',
    docs: '',
    paper: 'https://arxiv.org/abs/2208.04726',
    isPrivate: false,
    status: 'completed',
    year: '',
    team: 'solo',
    platform: ['Ubuntu 20/22', 'CUDA 11/12'],
    datasets: ['TartanAir', 'EuRoC', 'TUM-RGBD', 'ICL-NUIM', 'KITTI'],
    thumbnail: '',
    images: [],
    metrics: {}
  },

{
    id: 'droid_slam',
    cluster: 'robotics',
    name: 'DROID_slam',
    lang: 'Python',
    tagline: 'Deep Visual SLAM for Monocular, Stereo, and RGB-D Cameras',
    summary: 'A deep learning-based visual SLAM system (DROID-SLAM) capable of operating with monocular, stereo, and RGB-D cameras. It features an architecture utilizing dense bundle adjustment and learned features to achieve state-of-the-art trajectory estimation on datasets like TartanAir, EuRoC, TUM, and ETH3D.',
    highlights: [
      'Deep Visual SLAM architecture',
      'Supports Monocular, Stereo, and RGB-D inputs',
      'Asynchronous and Multi-GPU inference',
      'Evaluated on TartanAir, EuRoC, TUM-RGBD, and ETH3D'
    ],
    tech: ['Python', 'PyTorch', 'CUDA', 'Deep Learning', 'SLAM'],
    github: 'https://github.com/thippeswammy/DROID_slam',
    demo: '',
    docs: '',
    paper: 'https://arxiv.org/abs/2108.10869',
    isPrivate: false,
    status: 'completed',
    year: '',
    team: 'solo',
    platform: ['Ubuntu', 'CUDA'],
    datasets: ['TartanAir', 'EuRoC', 'TUM', 'ETH3D'],
    thumbnail: '',
    images: [],
    metrics: {}
  },

{
    id: 'elevation_mapping_cupy',
    cluster: 'robotics',
    name: 'elevation_mapping_cupy',
    lang: 'Python',
    tagline: 'Elevation Mapping for Locomotion and Navigation using GPU',
    summary: 'A robotic navigation and locomotion package integrating with ROS and utilizing GPU acceleration (CuPy). Enhances point cloud registration and ray casting for legged robots. Features Height Drift Compensation, Learning-based Traversability Filters, and a Multi-Modal Elevation Map (MEM) Framework for fusing geometry, semantics, and RGB information.',
    highlights: [
      'GPU-Accelerated Elevation Mapping using CuPy',
      'Multi-Modal Elevation Map (MEM) Framework',
      'Visibility Cleanup and Artifact Removal',
      'Learning-based Traversability Filter',
      'Plane Segmentation'
    ],
    tech: ['Python', 'CuPy', 'ROS', 'SLAM', 'CUDA'],
    github: 'https://github.com/thippeswammy/elevation_mapping_cupy',
    demo: '',
    docs: 'https://leggedrobotics.github.io/elevation_mapping_cupy/',
    paper: 'https://arxiv.org/abs/2204.12876',
    isPrivate: false,
    status: 'completed',
    year: '',
    team: 'team',
    platform: ['Ubuntu', 'ROS', 'CUDA'],
    datasets: [],
    thumbnail: '',
    images: ['docs/media/main_repo.png', 'docs/media/convex_approximation.gif'],
    metrics: {}
  },

{
    id: 'infratrackadas',
    cluster: 'robotics',
    name: 'InfratrackAdas',
    lang: 'Python',
    tagline: 'Offline-capable monocular-first road infrastructure auditing and behavioral intelligence system',
    summary: 'An advanced offline-capable road intelligence system that performs static infrastructure audits, road quality assessments, and dynamic vehicle/pedestrian tracking. Driven by sequential rosbag playback, it fuses SLAM visual odometry and GPS sensors to build a time-indexed Temporal Knowledge Graph (TKG) of the environment, triggering asynchronous VLM queries (Qwen-VL-2B) for detailed defect and anomaly reporting.',
    highlights: [
      'Static infrastructure auditing against expected OSM definitions and municipal rules',
      'Road quality assessment identifying potholes and surface cracks using SegFormer and VLM severity ratings',
      'Dynamic behavioral monitoring with YOLOv8n object detection and ByteTrack trajectory tracking',
      'Time-indexed Temporal Knowledge Graph (TKG) built with NetworkX to register entities and spatial-temporal states',
      'Monocular visual odometry drift correction using EasyOCR sign triangulation',
      'Interactive HTML Folium-based visualization with Google Maps overlays and heatmaps'
    ],
    tech: ['Python', 'ROS 2', 'RTAB-Map', 'YOLOv8', 'SegFormer', 'MiDaS', 'EasyOCR', 'Qwen-VL', 'NetworkX', 'Folium'],
    github: 'https://github.com/thippeswammy/InfratrackAdas',
    demo: '',
    docs: 'script/InfratrackAdas/project.md',
    paper: '',
    isPrivate: false,
    status: 'active',
    year: '2026',
    team: 'solo',
    platform: ['ROS 2', 'Linux', 'CUDA'],
    datasets: ['KITTI', 'nuScenes', 'CARLA'],
    thumbnail: '',
    images: [],
    metrics: {}
  },

{
    id: 'lanemappingtool',
    cluster: 'robotics',
    name: 'LaneMappingTool',
    lang: 'Python',
    tagline: 'Lane graph mapping for autonomous vehicles',
    summary: 'Transforms noisy recorded vehicle paths into structured graph-based lane networks with B-spline smoothing, junction logic, and a React+Flask web UI.',
    highlights: [
      'Graph-based lane network (nodes + edges)',
      'B-Spline path smoothing',
      'React + Vite frontend + Flask REST backend',
      'Deploys to AV stack via .pickle export'
    ],
    tech: ['python', 'react', 'flask', 'chart.js', 'adas', 'autonomous-driving'],
    github: 'https://github.com/thippeswammy/LaneMappingTool',
    demo: '',
    docs: '',
    paper: '',
    isPrivate: false,
    status: 'completed',
    year: '',
    team: 'solo',
    platform: ['Web', 'Windows', 'Linux'],
    datasets: [],
    thumbnail: '',
    images: [],
    metrics: {}
  },

{
    id: 'multiplevo',
    cluster: 'robotics',
    name: 'MultipleVo',
    lang: 'Python',
    tagline: 'Collection of Visual Odometry algorithms and implementations',
    summary: 'A repository containing various experiments and implementations of Monocular and Stereo Visual Odometry algorithms. It includes different approaches like Optical Flow-based VO, Stereo Odometry (SOFT), and Deep Learning enhanced VO (DFVO) blending classical techniques like Epipolar and PnP trackers with Neural Networks for depth and flow estimation.',
    highlights: [
      'Multiple Visual Odometry approaches (Monocular and Stereo)',
      'DFVO integration using E-tracker and PnP-tracker',
      'Optical Flow (dense) based monocular tracking',
      'Feature tracking with GFTT and RANSAC outlier rejection'
    ],
    tech: ['Python', 'OpenCV', 'Deep Learning', 'Computer Vision', 'Visual Odometry'],
    github: 'https://github.com/thippeswammy/MultipleVo',
    demo: '',
    docs: '',
    paper: '',
    isPrivate: false,
    status: 'completed',
    year: '',
    team: 'solo',
    platform: [],
    datasets: ['KITTI'],
    thumbnail: '',
    images: [],
    metrics: {}
  },

{
    id: 'my_bot',
    cluster: 'robotics',
    name: 'my_bot',
    lang: 'Python',
    tagline: 'Automated utility bot and script sandbox',
    summary: 'Sandbox for automation and scripting tests based on a ROS/robot package template.',
    highlights: [
      'Robot package template integration',
      'Automation script sandbox'
    ],
    tech: ['python', 'automation', 'ros'],
    github: 'https://github.com/thippeswammy/my_bot',
    demo: '',
    docs: '',
    paper: '',
    isPrivate: false,
    status: 'completed',
    year: '',
    team: 'solo',
    platform: [],
    datasets: [],
    thumbnail: '',
    images: [],
    metrics: {}
  },

{
    id: 'orb_slam2',
    cluster: 'robotics',
    name: 'ORB_SLAM2',
    lang: 'C++',
    tagline: 'Open-Source SLAM System for Monocular, Stereo and RGB-D Cameras',
    summary: 'ORB-SLAM2 is a versatile and accurate SLAM solution for Monocular, Stereo, and RGB-D cameras. It features real-time operation, Loop Closing, and Relocalization modes. Comes with examples for TUM, KITTI, and EuRoC datasets, and includes optional ROS nodes for live camera processing.',
    highlights: [
      'SLAM System for Monocular, Stereo and RGB-D cameras',
      'Real-time loop closing and relocalization',
      'Evaluated on TUM, KITTI, and EuRoC datasets',
      'Includes ROS nodes and Augmented Reality Demo'
    ],
    tech: ['C++', 'OpenCV', 'Eigen3', 'Pangolin', 'ROS', 'SLAM'],
    github: 'https://github.com/thippeswammy/ORB_SLAM2',
    demo: '',
    docs: '',
    paper: 'https://arxiv.org/abs/1610.06475',
    isPrivate: false,
    status: 'completed',
    year: '',
    team: 'team',
    platform: ['Ubuntu 14.04', 'Ubuntu 16.04', 'ROS'],
    datasets: ['TUM', 'KITTI', 'EuRoC'],
    thumbnail: '',
    images: [],
    metrics: {}
  },

{
    id: 'orb_slam3',
    cluster: 'robotics',
    name: 'ORB_SLAM3',
    lang: 'C++',
    tagline: 'Accurate Open-Source Library for Visual, Visual-Inertial and Multi-Map SLAM',
    summary: 'ORB-SLAM3 is an accurate open-source library for Visual, Visual-Inertial and Multi-Map SLAM. It supports monocular, stereo, RGB-D and inertial configurations. The system includes examples for popular datasets like EuRoC and TUM-VI, as well as ROS nodes for seamless integration.',
    highlights: [
      'Visual, Visual-Inertial, and Multi-Map SLAM',
      'Supports Monocular, Stereo, and RGB-D cameras',
      'Evaluations on EuRoC and TUM-VI datasets',
      'ROS nodes included for easy integration'
    ],
    tech: ['C++', 'OpenCV', 'Pangolin', 'Eigen3', 'ROS', 'SLAM'],
    github: 'https://github.com/thippeswammy/ORB_SLAM3',
    demo: '',
    docs: '',
    paper: 'https://arxiv.org/abs/2007.11898',
    isPrivate: false,
    status: 'completed',
    year: '',
    team: 'team',
    platform: ['Ubuntu 16.04', 'Ubuntu 18.04', 'ROS'],
    datasets: ['EuRoC', 'TUM-VI'],
    thumbnail: '',
    images: [],
    metrics: {}
  },

{
    id: 'orb_slam3_ros2',
    cluster: 'robotics',
    name: 'ORB_SLAM3_ROS2',
    lang: 'C++',
    tagline: 'ROS2 wrapping for ORB_SLAM3',
    summary: 'A ROS2 (Foxy) wrapper to use ORB_SLAM3. Supports Monocular, Stereo, RGB-D, and Stereo-Inertial SLAM modes. Integrated with ROS2 topics and message filters, providing a streamlined way to run state-of-the-art visual SLAM in modern ROS environments.',
    highlights: [
      'ROS2 wrapper for ORB_SLAM3',
      'Supports MONO, STEREO, RGBD, and STEREO-INERTIAL modes',
      'Compatible with ROS2 Foxy and OpenCV 4.2.0',
      'Includes instructions for bridging ROS1 rosbags (EuRoC dataset)'
    ],
    tech: ['C++', 'ROS2', 'ORB_SLAM3', 'OpenCV'],
    github: 'https://github.com/thippeswammy/ORB_SLAM3_ROS2',
    demo: '',
    docs: '',
    paper: '',
    isPrivate: false,
    status: 'completed',
    year: '',
    team: 'solo',
    platform: ['Ubuntu 20.04', 'ROS2'],
    datasets: ['EuRoC'],
    thumbnail: '',
    images: [],
    metrics: {}
  },

{
    id: 'rtab_ws',
    cluster: 'robotics',
    name: 'rtab_ws',
    lang: 'C++',
    tagline: 'RTAB-Map evaluation on KITTI Sequence 09',
    summary: 'A ROS workspace dedicated to evaluating the trajectory accuracy of Monocular and Stereo SLAM systems on the KITTI dataset (Sequence 09) using RTAB-Map. Tests various combinations of feature extractors (ORB, SIFT, BRISK, SuperPoint) and matchers (FLANN, SuperGlue).',
    highlights: [
      'RTAB-Map SLAM evaluation',
      'KITTI Sequence 09 trajectory accuracy testing',
      'Configurable Feature Extractors (ORB, SIFT, KAZE, SuperPoint) and Matchers'
    ],
    tech: ['C++', 'ROS', 'RTAB-Map', 'SLAM'],
    github: 'https://github.com/thippeswammy/rtab_ws',
    demo: '',
    docs: '',
    paper: '',
    isPrivate: false,
    status: 'completed',
    year: '',
    team: 'solo',
    platform: ['Ubuntu', 'ROS'],
    datasets: ['KITTI'],
    thumbnail: '',
    images: [],
    metrics: {}
  },

{
    id: 'rtabmap',
    cluster: 'robotics',
    name: 'rtabmap',
    lang: 'C++',
    tagline: 'RTAB-Map library and standalone application',
    summary: 'Source repository for RTAB-Map (Real-Time Appearance-Based Mapping). It is a RGB-D, Stereo and Lidar Graph-Based SLAM approach based on an incremental appearance-based loop closure detector. Supports ROS 1 and ROS 2.',
    highlights: [
      'RGB-D, Stereo and Lidar Graph-Based SLAM',
      'Incremental appearance-based loop closure detection',
      'Supports ROS 1 (Noetic) and ROS 2 (Humble, Jazzy, Rolling)',
      'Standalone application and library'
    ],
    tech: ['C++', 'ROS 1', 'ROS 2', 'SLAM', 'Docker'],
    github: 'https://github.com/thippeswammy/rtabmap',
    demo: '',
    docs: 'https://github.com/introlab/rtabmap/wiki',
    paper: '',
    isPrivate: false,
    status: 'completed',
    year: '',
    team: 'team',
    platform: ['Windows', 'Linux', 'ROS'],
    datasets: [],
    thumbnail: '',
    images: [],
    metrics: {}
  },

{
    id: 'rtabmap_ros',
    cluster: 'robotics',
    name: 'rtabmap_ros',
    lang: 'C++',
    tagline: 'ROS2 package for RTAB-Map',
    summary: 'The ROS2 wrapper and package for RTAB-Map. Supports ROS2 Humble, Jazzy, and Rolling. Includes sensor integration examples (stereo, RGB-D, 3D LiDAR) and robot integration examples (Turtlebot3, Turtlebot4, Nav2 integration).',
    highlights: [
      'ROS2 integration for RTAB-Map',
      'Supports sensor integration (stereo, RGB-D, LiDAR)',
      'Robot integration examples (Turtlebot, Nav2)'
    ],
    tech: ['C++', 'ROS 2', 'RTAB-Map', 'SLAM'],
    github: 'https://github.com/thippeswammy/rtabmap_ros',
    demo: '',
    docs: 'http://wiki.ros.org/rtabmap_ros',
    paper: '',
    isPrivate: false,
    status: 'completed',
    year: '',
    team: 'team',
    platform: ['Ubuntu', 'ROS 2'],
    datasets: [],
    thumbnail: '',
    images: [],
    metrics: {}
  },

{
    id: 'sdf_to_nav_mesh',
    cluster: 'robotics',
    name: 'sdf_to_nav_mesh',
    lang: 'Python',
    tagline: 'SDF world → navigation mesh converter for ROS 2',
    summary: 'A standalone ROS 2 tool to convert Gazebo SDF/World files into Navigation Mesh assets (.ply, .dae, .h5). Automatically extracts geometry from SDF files, generates high-resolution navigation meshes, and injects metadata (normals, roughness) into HDF5 maps for autonomous navigation pipelines.',
    highlights: [
      'Gazebo SDF → PLY/DAE/H5 pipeline',
      'Terrain metadata extraction (roughness, steepness)',
      'ROS 2 (Humble) native integration',
      'Mesh-based AV navigation support'
    ],
    tech: ['Python', 'ROS 2', 'Gazebo', 'h5py', 'trimesh', 'shapely'],
    github: 'https://github.com/thippeswammy/sdf_to_nav_mesh',
    demo: '',
    docs: '',
    paper: '',
    isPrivate: false,
    status: 'completed',
    year: '',
    team: 'solo',
    platform: ['Ubuntu 22.04', 'ROS 2 Humble'],
    datasets: [],
    thumbnail: '',
    images: [],
    metrics: {}
  },

{
    id: 'semantic_robot_perception',
    cluster: 'robotics',
    name: 'semantic-robot-perception',
    lang: 'C++',
    tagline: 'ROS 2 mobile robot navigation stack with real-time 3D spatial semantic mapping',
    summary: 'A comprehensive ROS 2 Humble & Gazebo simulation stack for differential drive robots. Combines an optimized, physics-stabilized URDF model with a complete 3D spatial semantic mapping and perception suite. Using open-vocabulary YOLO-World and LiDAR range sweeps, the system performs camera pinhole inverse depth projection to build a persistent 3D database of environment objects, visualized dynamically in RViz.',
    highlights: [
      'Autonomous SLAM navigation using Nav2 and physical physics stabilization in Gazebo',
      'Open-vocabulary object recognition using YOLO-World and spatial centroid tracking',
      'Real-time LiDAR-camera fusion for pinhole inverse depth projection',
      'Dynamic 3D database of semantic obstacles with orientation, count, and confidence metrics',
      'Interactive RViz3D visualization with custom MarkerArray nodes and live camera overlays'
    ],
    tech: ['C++', 'Python', 'ROS 2 Humble', 'Gazebo', 'YOLO-World', 'SLAM', 'LiDAR', 'RViz'],
    github: 'https://github.com/thippeswammy/semantic-robot-perception',
    demo: '',
    docs: 'script/semantic-robot-perception/README.md',
    paper: '',
    isPrivate: false,
    status: 'completed',
    year: '2026',
    team: 'solo',
    platform: ['ROS 2 Humble', 'Linux'],
    datasets: ['Gazebo Simulated Worlds'],
    thumbnail: '',
    images: [],
    metrics: {}
  },

{
    id: 'vo2map',
    cluster: 'robotics',
    name: 'VO2MAP',
    lang: '',
    tagline: 'VO2MAP Project',
    summary: 'Visual Odometry to Map (VO2MAP) project.',
    highlights: [],
    tech: [],
    github: 'https://github.com/thippeswammy/VO2MAP',
    demo: '',
    docs: '',
    paper: '',
    isPrivate: false,
    status: 'completed',
    year: '',
    team: 'solo',
    platform: [],
    datasets: [],
    thumbnail: '',
    images: [],
    metrics: {}
  },


  // ── EMBEDDED & HARDWARE ────────────────────────────────────────────────────────────────
{
    id: 'arduino',
    cluster: 'embedded',
    name: 'Arduino',
    lang: 'C++',
    tagline: 'Arduino projects repository',
    summary: 'A collection of various Arduino projects including Face Tracking, Traffic Signal, CAN Communication, Obstacle Avoidance Car, Servo Control, Smart Water Manager, LCD interactions, and Ultrasonic Object Counter.',
    highlights: [
      'Face Tracking System',
      'CAN Communication implementation',
      'Obstacle Avoidance Car',
      'Smart Water Manager'
    ],
    tech: ['C++', 'Arduino', 'Hardware'],
    github: 'https://github.com/thippeswammy/Arduino',
    demo: '',
    docs: '',
    paper: '',
    isPrivate: false,
    status: 'completed',
    year: '',
    team: 'solo',
    platform: ['Arduino'],
    datasets: [],
    thumbnail: '',
    images: [],
    metrics: {}
  },

{
    id: 'dspace',
    cluster: 'embedded',
    name: 'dSPACE',
    lang: '',
    tagline: 'dSPACE project',
    summary: 'dSPACE project repository.',
    highlights: [],
    tech: [],
    github: 'https://github.com/thippeswammy/dSPACE',
    demo: '',
    docs: '',
    paper: '',
    isPrivate: false,
    status: 'completed',
    year: '',
    team: 'solo',
    platform: [],
    datasets: [],
    thumbnail: '',
    images: [],
    metrics: {}
  },

{
    id: 'eceproject',
    cluster: 'embedded',
    name: 'EceProject',
    lang: 'C++',
    tagline: 'Electronics & Computer Engineering Workspace',
    summary: 'A comprehensive collection of engineering projects spanning Computer Vision, Embedded Systems, and Robotics. Includes Arduino-based CV projects like Face/Fire tracking using YOLOv8, and integration across ESP8266, Raspberry Pi, and stereo camera setups.',
    highlights: [
      'Arduino-based Computer Vision projects',
      'Face and Fire tracking using YOLOv8',
      'Gesture Recognition and Hardware Control via Python serial comms',
      'Integration with ESP8266 and Raspberry Pi'
    ],
    tech: ['C++', 'Arduino', 'Python', 'YOLOv8', 'Computer Vision', 'Embedded Systems'],
    github: 'https://github.com/thippeswammy/EceProject',
    demo: '',
    docs: '',
    paper: '',
    isPrivate: false,
    status: 'completed',
    year: '',
    team: 'solo',
    platform: ['Arduino', 'Raspberry Pi', 'ESP8266'],
    datasets: [],
    thumbnail: '',
    images: [],
    metrics: {}
  },

{
    id: 'matlabmodels',
    cluster: 'embedded',
    name: 'MatlabModels',
    lang: 'MATLAB',
    tagline: 'MATLAB and Simulink-based embedded and automotive modeling',
    summary: 'A collection of MATLAB and Simulink-based projects focused on embedded systems, automotive behavioral modeling, real-time control systems, and hardware interfacing using platforms like Arduino, Raspberry Pi, STM32, and dSPACE.',
    highlights: [
      'Automotive behavioral modeling (steering, brakes, dashboard)',
      'Embedded hardware integration (Arduino, Raspberry Pi, STM32)',
      'dSPACE Real-Time Projects (HIL concepts)',
      'Sensor and actuator integration'
    ],
    tech: ['MATLAB', 'Simulink', 'Arduino', 'Raspberry Pi', 'STM32', 'dSPACE'],
    github: 'https://github.com/thippeswammy/MatlabModels',
    demo: '',
    docs: '',
    paper: '',
    isPrivate: false,
    status: 'completed',
    year: '',
    team: 'solo',
    platform: [],
    datasets: [],
    thumbnail: '',
    images: [],
    metrics: {}
  },

{
    id: 'mbd_dspace',
    cluster: 'embedded',
    name: 'MBD-dSPACE',
    lang: 'MATLAB',
    tagline: 'Model-Based Design and dSPACE Work',
    summary: 'Repository for Model-Based Design (MBD) and dSPACE projects, including Vehicle Behavioral Modeling and vehicle controller implementation.',
    highlights: [
      'Model-Based Design (MBD)',
      'Vehicle Behavioral Modeling',
      'dSPACE integration'
    ],
    tech: ['MATLAB', 'Simulink', 'dSPACE'],
    github: 'https://github.com/thippeswammy/MBD-dSPACE',
    demo: '',
    docs: '',
    paper: '',
    isPrivate: false,
    status: 'completed',
    year: '',
    team: 'solo',
    platform: [],
    datasets: [],
    thumbnail: '',
    images: [],
    metrics: {}
  },


  // ── DESKTOP APPLICATIONS & SOFTWARE ────────────────────────────────────────────────────────────────
{
    id: 'basicmathcalculatorapp',
    cluster: 'software',
    name: 'BasicMathCalculatorApp',
    lang: 'Java',
    tagline: 'A simple Java calculator application',
    summary: 'A simple Java calculator application built with Swing. It performs basic arithmetic operations (+, -, *, /) between two numbers. Developed in IntelliJ IDEA.',
    highlights: [
      'Basic arithmetic operations',
      'Java Swing GUI'
    ],
    tech: ['Java', 'Swing', 'IntelliJ IDEA'],
    github: 'https://github.com/thippeswammy/BasicMathCalculatorApp',
    demo: '',
    docs: '',
    paper: '',
    isPrivate: false,
    status: 'completed',
    year: '',
    team: 'solo',
    platform: ['Windows', 'Linux', 'macOS'],
    datasets: [],
    thumbnail: '',
    images: [],
    metrics: {}
  },

{
    id: 'calculatorguiapp',
    cluster: 'software',
    name: 'CalculatorGuiApp',
    lang: 'Java',
    tagline: 'A simple GUI-based Java calculator app',
    summary: 'A simple and intuitive Calculator App implemented in Java with a graphical user interface using NetBeans. It offers standard mathematical operations and showcases GUI development techniques and logic implementation.',
    highlights: [
      'Graphical user interface developed in NetBeans',
      'Standard mathematical operations'
    ],
    tech: ['Java', 'NetBeans', 'Java GUI'],
    github: 'https://github.com/thippeswammy/CalculatorGuiApp',
    demo: '',
    docs: '',
    paper: '',
    isPrivate: false,
    status: 'completed',
    year: '',
    team: 'solo',
    platform: ['Windows', 'Linux', 'macOS'],
    datasets: [],
    thumbnail: '',
    images: [],
    metrics: {}
  },

{
    id: 'datavisualizationeditingtool',
    cluster: 'software',
    name: 'DataVisualizationEditingTool',
    lang: 'Python',
    tagline: 'Python-based tool for visualizing and editing lane data',
    summary: 'A Python-based application designed for visualizing, editing, and managing lane data stored in NumPy (.npy) files. It provides an interactive Matplotlib interface for users to manipulate lane points, merge lanes, smooth segments, and draw new lanes, ideal for tasks like annotating road lanes for autonomous driving.',
    highlights: [
      'Interactive visualization of lane data',
      'Edit, merge, and smooth lane points',
      'Draw new lanes and export data',
      'Undo/redo operations and auto-save backups'
    ],
    tech: ['Python', 'Matplotlib', 'NumPy'],
    github: 'https://github.com/thippeswammy/DataVisualizationEditingTool',
    demo: '',
    docs: '',
    paper: '',
    isPrivate: false,
    status: 'completed',
    year: '',
    team: 'solo',
    platform: ['Windows', 'Linux'],
    datasets: [],
    thumbnail: '',
    images: [],
    metrics: {}
  },

{
    id: 'jarviscontrolsystem',
    cluster: 'software',
    name: 'JarvisControlSystem',
    lang: 'Python',
    tagline: 'An advanced, autonomous virtual assistant and desktop agent',
    summary: 'An advanced, autonomous virtual assistant system inspired by J.A.R.V.I.S from Iron Man. It is a self-aware, state-persistent, and fully autonomous desktop agent built on the robust v2.1 "Iron Man" Architecture. It provides seamless, hands-free automation of the digital workspace by decoupling cognitive intent from physical execution.',
    highlights: [
      'Orchestrator brain and continuous Verification Loop',
      'Powered by local LLMs (like Ollama/gemma3)',
      'State-Aware Delta Navigation (Look-Before-You-Leap execution)',
      'Self-Learning Semantic Macros stored in a Graph DB',
      '5-layer persistent memory model with a RAG context pipeline',
      'Telegram bot integration for remote control'
    ],
    tech: ['Python', 'LLM', 'Ollama', 'RAG', 'Graph DB', 'Telegram API'],
    github: 'https://github.com/thippeswammy/JarvisControlSystem',
    demo: '',
    docs: '',
    paper: '',
    isPrivate: false,
    status: 'ongoing',
    year: '',
    team: 'solo',
    platform: ['Windows'],
    datasets: [],
    thumbnail: '',
    images: [],
    metrics: {}
  },

{
    id: 'loginsystemwithadvancegui',
    cluster: 'software',
    name: 'LoginSystemWithAdvanceGUI',
    lang: 'Java',
    tagline: 'Advanced Login System with Java GUI',
    summary: 'An advanced Login System developed using Java and GUI in NetBeans. It features a user-friendly interface for intuitive user interaction and implements user authentication principles.',
    highlights: [
      'Advanced GUI design',
      'User authentication implementation',
      'Developed in NetBeans IDE'
    ],
    tech: ['Java', 'NetBeans', 'Java GUI'],
    github: 'https://github.com/thippeswammy/LoginSystemWithAdvanceGUI',
    demo: '',
    docs: '',
    paper: '',
    isPrivate: false,
    status: 'completed',
    year: '',
    team: 'solo',
    platform: ['Windows', 'Linux', 'macOS'],
    datasets: [],
    thumbnail: '',
    images: ['https://github.com/thippeswammy/LoginSystemWithAdvanceGUI/assets/73697198/dd0ad50c-5c3c-4ada-9986-ab4e0b86a7fd'],
    metrics: {}
  },

{
    id: 'loginsystemwithgui',
    cluster: 'software',
    name: 'LoginSystemWithGUI',
    lang: 'Java',
    tagline: 'A simple Java Swing user authentication application',
    summary: 'A simple Java Swing application for user authentication and login functionality, built using NetBeans. Features a user-friendly graphical interface with intuitive controls, ideal for learning basic login system concepts and GUI development.',
    highlights: [
      'User authentication and login functionality',
      'Graphical interface with intuitive controls',
      'Built using NetBeans IDE'
    ],
    tech: ['Java', 'Java Swing', 'NetBeans'],
    github: 'https://github.com/thippeswammy/LoginSystemWithGUI',
    demo: '',
    docs: '',
    paper: '',
    isPrivate: false,
    status: 'completed',
    year: '',
    team: 'solo',
    platform: ['Windows', 'Linux', 'macOS'],
    datasets: [],
    thumbnail: '',
    images: ['https://github.com/thippeswammy/LoginSystemWithGUI/assets/73697198/b2d698ec-6c33-400e-9167-eb5d726ef31d'],
    metrics: {}
  },

{
    id: 'multiapprunnerloginauth',
    cluster: 'software',
    name: 'MultiAppRunnerLoginAuth',
    lang: 'Java',
    tagline: 'Login-controlled application runner',
    summary: 'A project developed in IntelliJ IDEA and NetBeans featuring a login system that controls access to various functionalities and allows users to run specific applications based on successful authentication.',
    highlights: [
      'Login-based access control',
      'Runs specific applications post-authentication',
      'Cross-platform compatibility'
    ],
    tech: ['Java', 'IntelliJ IDEA', 'NetBeans'],
    github: 'https://github.com/thippeswammy/MultiAppRunnerLoginAuth',
    demo: '',
    docs: '',
    paper: '',
    isPrivate: false,
    status: 'completed',
    year: '',
    team: 'solo',
    platform: ['Windows', 'Linux', 'macOS'],
    datasets: [],
    thumbnail: '',
    images: [],
    metrics: {}
  },

{
    id: 'neetcodeproblems',
    cluster: 'software',
    name: 'NeetCodeProblems',
    lang: 'Java',
    tagline: 'Optimized Java & Kotlin solutions for LeetCode and DSA interview preparation',
    summary: 'A robust repository containing clean, well-documented solutions to competitive coding and Data Structures & Algorithms (DSA) interview problems from platforms like LeetCode and NeetCode. Written in Java and Kotlin, focusing on efficient runtime and space complexities.',
    highlights: [
      'Optimized solutions in both Java and Kotlin',
      'Covers Arrays, Strings, Linked Lists, Trees, Graphs, and DP',
      'Implementations focused on time and space complexity efficiency',
      'Designed for interview preparation and DSA problem-solving mastery'
    ],
    tech: ['Java', 'Kotlin', 'Algorithms', 'Data Structures'],
    github: 'https://github.com/thippeswammy/NeetCodeProblems',
    demo: '',
    docs: '',
    paper: '',
    isPrivate: false,
    status: 'completed',
    year: '',
    team: 'solo',
    platform: [],
    datasets: [],
    thumbnail: '',
    images: [],
    metrics: {}
  },

{
    id: 'secureapplocker',
    cluster: 'software',
    name: 'SecureAppLocker',
    lang: 'Java',
    tagline: 'An application locker developed in IntelliJ IDEA',
    summary: 'An application developed in IntelliJ IDEA that serves as a locker for other applications. To access the locked applications, users need to run a Login System, and upon successful authentication, they gain access to the desired files.',
    highlights: [
      'Locks applications behind authentication',
      'Integration with a Login System'
    ],
    tech: ['Java', 'IntelliJ IDEA'],
    github: 'https://github.com/thippeswammy/SecureAppLocker',
    demo: '',
    docs: '',
    paper: '',
    isPrivate: false,
    status: 'completed',
    year: '',
    team: 'solo',
    platform: ['Windows', 'Linux', 'macOS'],
    datasets: [],
    thumbnail: '',
    images: [],
    metrics: {}
  },

{
    id: 'simplecontactsmanager',
    cluster: 'software',
    name: 'SimpleContactsManager',
    lang: 'Java',
    tagline: 'Text-based contacts and message manager',
    summary: 'A text-based application built in IntelliJ IDEA for managing contacts and messages. Offers features like adding, viewing, searching, and deleting contacts, as well as sending and receiving messages within the console interface.',
    highlights: [
      'Manage contacts (add, view, search, delete)',
      'Send and receive messages in console',
      'Text-based Java application'
    ],
    tech: ['Java', 'IntelliJ IDEA'],
    github: 'https://github.com/thippeswammy/SimpleContactsManager',
    demo: '',
    docs: '',
    paper: '',
    isPrivate: false,
    status: 'completed',
    year: '',
    team: 'solo',
    platform: ['Console'],
    datasets: [],
    thumbnail: '',
    images: [],
    metrics: {}
  },


  // ── MOBILE & AUGMENTED REALITY ────────────────────────────────────────────────────────────────
{
    id: 'ar_cube_drop',
    cluster: 'mobile',
    name: 'AR-Cube-Drop',
    lang: 'C#',
    tagline: 'Unity ARFoundation Cube Placement application',
    summary: 'A Unity project demonstrating an AR application built using ARFoundation. It allows users to place cubes of random colors at tapped screen locations (2 meters in front of the camera) and automatically captures an image of the AR scene shortly after placement.',
    highlights: [
      'AR Cube Placement with random colors',
      'Automatic Image Capture of the AR scene',
      'Built with Unity ARFoundation and ARSubsystems',
      'Supports Android and iOS deployment'
    ],
    tech: ['C#', 'Unity', 'ARFoundation', 'ARSubsystems'],
    github: 'https://github.com/thippeswammy/AR-Cube-Drop',
    demo: '',
    docs: '',
    paper: '',
    isPrivate: false,
    status: 'completed',
    year: '',
    team: 'solo',
    platform: ['Android', 'iOS'],
    datasets: [],
    thumbnail: '',
    images: ['https://github.com/user-attachments/assets/dcd4e682-d3f9-434f-8429-ac4e20d070e1'],
    metrics: {}
  },

{
    id: 'speechcalculator',
    cluster: 'mobile',
    name: 'SpeechCalculator',
    lang: 'Java',
    tagline: 'Android app combining voice and calculator',
    summary: 'An innovative Android app developed in Android Studio that combines the power of voice with a user-friendly calculator interface. Users can speak their calculations and get instant results using built-in speech recognition and ArrayList-based expression evaluation.',
    highlights: [
      'Speech Recognition for voice-based calculations',
      'Advanced calculation with priority evaluation',
      'Published on Google Play Store'
    ],
    tech: ['Java', 'Android SDK', 'Android Studio'],
    github: 'https://github.com/thippeswammy/SpeechCalculator',
    demo: 'https://play.google.com/store/apps/details?id=com.Thippeswamy.calculator',
    docs: '',
    paper: '',
    isPrivate: false,
    status: 'completed',
    year: '',
    team: 'solo',
    platform: ['Android'],
    datasets: [],
    thumbnail: '',
    images: ['https://github.com/thippeswammy/SpeechCalculator/assets/73697198/0030fa19-0252-4b09-a098-6440351012de'],
    metrics: {}
  },

{
    id: 'connect2park',
    cluster: 'mobile',
    name: 'Smart Car Parking System',
    lang: 'Java',
    tagline: 'Real-time parking space finder and booking application using Android and Firebase',
    summary: 'An advanced, real-time smart parking management application built on Android. It allows drivers to dynamically search, book, and navigate to vacant parking slots using Google Maps API. It integrates Firebase Firestore for live synchronization of slot occupancy, secure payment gateway APIs, and support for IoT sensor arrays and AI-based parking lot camera updates.',
    highlights: [
      'Real-time slot availability tracking with live Firebase Firestore database synchronization',
      'Secure in-app parking reservation and transaction processing',
      'Google Maps API integration for location searches and turn-by-turn navigation',
      'Analytics dashboard for parking managers to monitor occupancy rates and revenues',
      'Optional support for physical IoT slot sensors and automated AI camera detections'
    ],
    tech: ['Java', 'Android Studio', 'Firebase Firestore', 'Firebase Auth', 'Google Maps API', 'IoT'],
    github: 'https://github.com/thippeswammy/SmartParking',
    demo: '',
    docs: 'script/connect2park/README.md',
    paper: '',
    isPrivate: false,
    status: 'completed',
    year: '2025',
    team: 'solo',
    platform: ['Android'],
    datasets: [],
    thumbnail: '',
    images: [],
    metrics: {}
  },


  // ── GAMES & INTERACTIVE ────────────────────────────────────────────────────────────────
{
    id: '3d_car_racing_game',
    cluster: 'games',
    name: '3D-Car-racing-game',
    lang: 'C#',
    tagline: 'Thrilling 3D car racing game developed in Unity',
    summary: 'A thrilling 3D car racing game developed in Unity, featuring multiple cars, dynamic environments, sound effects, and navigation graphics. It includes automatic scaling for all screen resolutions and person character control.',
    highlights: [
      'Multiple Cars and Dynamic Environments',
      'Realistic Sound Effects and Navigation Graphics',
      'Automatic Screen Resolution Scaling',
      'Person Character Control mode',
      'Exported for Windows (.exe) and Android (.apk)'
    ],
    tech: ['C#', 'Unity', '3D Graphics'],
    github: 'https://github.com/thippeswammy/3D-Car-racing-game',
    demo: '',
    docs: '',
    paper: '',
    isPrivate: false,
    status: 'completed',
    year: '',
    team: 'solo',
    platform: ['Windows', 'Android'],
    datasets: [],
    thumbnail: '',
    images: [
      'https://github.com/thippeswammy/3D-Car-racing-game/assets/73697198/41084c0b-0ec9-4d83-960e-ed4c2af02637',
      'https://github.com/thippeswammy/3D-Car-racing-game/assets/73697198/ee48aa28-b715-479f-859b-706cdcd7742c'
    ],
    metrics: {}
  },

{
    id: 'ballonblastgame',
    cluster: 'games',
    name: 'BallonBlastGame',
    lang: 'Java',
    tagline: 'Exciting balloon popping game',
    summary: 'Blast your way through colorful balloons in this exciting game developed using Greenfoot. It offers dynamic gameplay with engaging mechanics to learn Java programming fundamentals while having a blast!',
    highlights: [
      'Dynamic balloon popping gameplay',
      'Developed with Greenfoot'
    ],
    tech: ['Java', 'Greenfoot'],
    github: 'https://github.com/thippeswammy/BallonBlastGame',
    demo: '',
    docs: '',
    paper: '',
    isPrivate: false,
    status: 'completed',
    year: '',
    team: 'solo',
    platform: [],
    datasets: [],
    thumbnail: '',
    images: [],
    metrics: {}
  },

{
    id: 'brickgame',
    cluster: 'games',
    name: 'BrickGame',
    lang: 'Java',
    tagline: 'Classic brick breaking game',
    summary: 'An interactive game developed using Greenfoot, where players can enjoy breaking bricks in a challenging environment.',
    highlights: [
      'Brick breaking gameplay',
      'Developed with Greenfoot'
    ],
    tech: ['Java', 'Greenfoot'],
    github: 'https://github.com/thippeswammy/BrickGame',
    demo: '',
    docs: '',
    paper: '',
    isPrivate: false,
    status: 'completed',
    year: '',
    team: 'solo',
    platform: [],
    datasets: [],
    thumbnail: '',
    images: [],
    metrics: {}
  },

{
    id: 'chainreactiongame',
    cluster: 'games',
    name: 'ChainReactionGame',
    lang: 'Java',
    tagline: 'A strategic multiplayer chain reaction game',
    summary: 'A strategic multiplayer game developed using the GreenFoot library. Players strategically place orbs on a grid, which release energy in multiple directions to trigger a chain reaction with the goal of capturing opponent orbs.',
    highlights: [
      'Multiplayer Functionality',
      'Intuitive User Interface',
      'Dynamic Physics for chain reactions',
      'Built using GreenFoot'
    ],
    tech: ['Java', 'Greenfoot', 'NetBeans'],
    github: 'https://github.com/thippeswammy/ChainReactionGame',
    demo: '',
    docs: '',
    paper: '',
    isPrivate: false,
    status: 'completed',
    year: '',
    team: 'solo',
    platform: ['Windows', 'Linux', 'macOS'],
    datasets: [],
    thumbnail: '',
    images: ['https://github.com/thippeswammy/ChainReactionGame/assets/73697198/a9fddf5f-39e9-40e8-959f-871f95dea120'],
    metrics: {}
  },

{
    id: 'downshootergame',
    cluster: 'games',
    name: 'DownShooterGame',
    lang: 'Java',
    tagline: 'An action-packed doggo shooter game',
    summary: 'Join the heroic doggo in this action-packed shooter game developed using Greenfoot. Defend your territory against enemies with strategic shooting and cunning maneuvers while discovering a pixel-perfect art style.',
    highlights: [
      'Strategic shooting and maneuvering',
      'Pixel-perfect art style',
      'Developed with Greenfoot'
    ],
    tech: ['Java', 'Greenfoot'],
    github: 'https://github.com/thippeswammy/DownShooterGame',
    demo: '',
    docs: '',
    paper: '',
    isPrivate: false,
    status: 'completed',
    year: '',
    team: 'solo',
    platform: [],
    datasets: [],
    thumbnail: '',
    images: [],
    metrics: {}
  },

{
    id: 'flappy_bird_game',
    cluster: 'games',
    name: 'Flappy-bird-game',
    lang: 'Java',
    tagline: 'Classic Flappy Bird clone developed using Greenfoot',
    summary: 'A classic Flappy Bird game project developed using the Greenfoot libraries. Players take control of a bird, guiding it through a series of obstacles with the press of keys to accumulate points and achieve high scores.',
    highlights: [
      'Classic Flappy Bird gameplay mechanics',
      'High Score Challenge',
      'Developed with Greenfoot'
    ],
    tech: ['Java', 'Greenfoot'],
    github: 'https://github.com/thippeswammy/Flappy-bird-game',
    demo: '',
    docs: '',
    paper: '',
    isPrivate: false,
    status: 'completed',
    year: '2019',
    team: 'solo',
    platform: ['Windows', 'Linux', 'macOS'],
    datasets: [],
    thumbnail: '',
    images: ['https://github.com/thippeswammy/Flappy-bird-game/assets/73697198/66d3f4aa-b978-42de-9098-f8d16850bac9'],
    metrics: {}
  },

{
    id: 'handcricketgame',
    cluster: 'games',
    name: 'HandCricketGame',
    lang: 'Java',
    tagline: 'Interactive Hand Cricket Game',
    summary: 'A fun and interactive Hand Cricket Game developed in IntelliJ IDEA. Swing, spin, and score runs with this entertaining cricket game played with gestures.',
    highlights: [
      'Digital hand cricket match experience',
      'Developed using IntelliJ IDEA'
    ],
    tech: ['Java', 'IntelliJ IDEA'],
    github: 'https://github.com/thippeswammy/HandCricketGame',
    demo: '',
    docs: '',
    paper: '',
    isPrivate: false,
    status: 'completed',
    year: '',
    team: 'solo',
    platform: [],
    datasets: [],
    thumbnail: '',
    images: [],
    metrics: {}
  },

{
    id: 'maze_game',
    cluster: 'games',
    name: 'Maze-game',
    lang: 'Java',
    tagline: 'Exciting maze-navigating adventure game',
    summary: 'A maze-navigating adventure game developed using the Greenfoot libraries. Players explore a maze, munch on food to boost speed, and dodge enemies en route to the endpoints.',
    highlights: [
      'Maze navigation and exploration',
      'Speed boosts from food items',
      'Enemy evasion mechanics',
      'Developed using Greenfoot'
    ],
    tech: ['Java', 'Greenfoot'],
    github: 'https://github.com/thippeswammy/Maze-game',
    demo: '',
    docs: '',
    paper: '',
    isPrivate: false,
    status: 'completed',
    year: '',
    team: 'solo',
    platform: ['Windows', 'Linux', 'macOS'],
    datasets: [],
    thumbnail: '',
    images: ['https://github.com/thippeswammy/Maze-game/assets/73697198/8968dca9-a3a5-4c50-ae07-9ad5786a8875'],
    metrics: {}
  },

{
    id: 'numberguessergame',
    cluster: 'games',
    name: 'NumberGuesserGame',
    lang: 'Java',
    tagline: 'A simple number guessing game with difficulty levels',
    summary: 'A challenging number guessing game written in Java. Features multiple difficulty levels and leaderboards to test your intuition and climb the ranks.',
    highlights: [
      'Number guessing gameplay',
      'Multiple difficulty levels',
      'Leaderboard functionality'
    ],
    tech: ['Java'],
    github: 'https://github.com/thippeswammy/NumberGuesserGame',
    demo: '',
    docs: '',
    paper: '',
    isPrivate: false,
    status: 'completed',
    year: '',
    team: 'solo',
    platform: [],
    datasets: [],
    thumbnail: '',
    images: [],
    metrics: {}
  },

{
    id: 'puzzle_game',
    cluster: 'games',
    name: 'Puzzle-game',
    lang: 'Java',
    tagline: 'Number Grid Puzzle Game',
    summary: 'A Java Swing game developed in NetBeans offering an interactive experience where players arrange numbers in ascending order within a grid. Features randomized grid placement, grid sizes from 3x3 to 6x6, and move analysis to provide hints.',
    highlights: [
      'Interactive number grid puzzle',
      'Randomized grid placement',
      'Supports varying grid sizes (3x3 to 6x6)',
      'Built using Java Swing'
    ],
    tech: ['Java', 'Swing', 'NetBeans'],
    github: 'https://github.com/thippeswammy/Puzzle-game',
    demo: '',
    docs: '',
    paper: '',
    isPrivate: false,
    status: 'completed',
    year: '',
    team: 'solo',
    platform: ['Windows', 'Linux', 'macOS'],
    datasets: [],
    thumbnail: '',
    images: ['https://github.com/thippeswammy/Puzzle-game/assets/73697198/713d6dba-41b4-4dc4-9b3f-421918cb55e4'],
    metrics: {}
  },

{
    id: 'snake_gui_game',
    cluster: 'games',
    name: 'Snake-GUI-game',
    lang: 'Java',
    tagline: 'Classic Snake Game implemented with Java Swing GUI',
    summary: 'A classic Snake Game implemented in Java with a graphical user interface using NetBeans. Utilizes Swing components for the GUI, custom painting for graphics, and a Swing Timer to manage the game loop and logic.',
    highlights: [
      'Swing Framework and Custom Painting',
      'Event Handling and Game Logic (collisions, movement)',
      'Game loop using Swing Timer'
    ],
    tech: ['Java', 'Swing', 'NetBeans'],
    github: 'https://github.com/thippeswammy/Snake-GUI-game',
    demo: '',
    docs: '',
    paper: '',
    isPrivate: false,
    status: 'completed',
    year: '',
    team: 'solo',
    platform: ['Windows', 'Linux', 'macOS'],
    datasets: [],
    thumbnail: '',
    images: ['https://github.com/thippeswammy/SnakeGUI/assets/73697198/35d862e5-0382-452f-8423-a39708b0ebf6'],
    metrics: {}
  },

{
    id: 'supermariogame',
    cluster: 'games',
    name: 'SuperMarioGame',
    lang: 'Java',
    tagline: 'A classic side-scrolling platformer game inspired by Super Mario',
    summary: 'A classic side-scrolling platformer game inspired by Super Mario, built using Greenfoot. Embark on an adventure, defeat enemies, and navigate through challenging levels in this nostalgic gaming experience.',
    highlights: [
      'Side-scrolling platformer gameplay',
      'Enemy interactions and defeats',
      'Level navigation',
      'Built with Greenfoot'
    ],
    tech: ['Java', 'Greenfoot'],
    github: 'https://github.com/thippeswammy/SuperMarioGame',
    demo: '',
    docs: '',
    paper: '',
    isPrivate: false,
    status: 'completed',
    year: '',
    team: 'solo',
    platform: [],
    datasets: [],
    thumbnail: '',
    images: [],
    metrics: {}
  },

{
    id: 'textbasedtictactoe',
    cluster: 'games',
    name: 'TextBasedTicTacToe',
    lang: 'Java',
    tagline: 'Console-based Tic Tac Toe game',
    summary: 'A simple console-based Tic Tac Toe game implemented in Java using IntelliJ IDEA. Play the classic X & O game with pure console input and output. Supports single-player vs AI (with varying difficulty levels) and two-player modes.',
    highlights: [
      'Single-player vs AI and two-player modes',
      'Varying difficulty levels for AI',
      'Console-based input/output'
    ],
    tech: ['Java', 'IntelliJ IDEA'],
    github: 'https://github.com/thippeswammy/TextBasedTicTacToe',
    demo: '',
    docs: '',
    paper: '',
    isPrivate: false,
    status: 'completed',
    year: '',
    team: 'solo',
    platform: ['Windows', 'Linux', 'macOS', 'Console'],
    datasets: [],
    thumbnail: '',
    images: [],
    metrics: {}
  },

{
    id: 'tictactoegui',
    cluster: 'games',
    name: 'TicTacToeGUI',
    lang: 'Java',
    tagline: 'Tic Tac Toe game with a graphical user interface',
    summary: 'A Tic Tac Toe game with a graphical user interface (GUI) developed using Java in NetBeans. It features an intuitive interface and a formidable AI opponent programmed with winning strategies.',
    highlights: [
      'Graphical User Interface using Java Swing',
      'AI opponent with winning strategies',
      'Developed in NetBeans IDE'
    ],
    tech: ['Java', 'NetBeans', 'Java Swing'],
    github: 'https://github.com/thippeswammy/TicTacToeGUI',
    demo: '',
    docs: '',
    paper: '',
    isPrivate: false,
    status: 'completed',
    year: '',
    team: 'solo',
    platform: ['Windows', 'Linux', 'macOS'],
    datasets: [],
    thumbnail: '',
    images: ['https://github.com/thippeswammy/TicTacToeGUI/assets/73697198/bc6e63ed-d106-4815-b832-6dc535737ea4'],
    metrics: {}
  },


  // ── DEV TOOLS & RESEARCH ────────────────────────────────────────────────────────────────
{
    id: 'deep_learning_specialization',
    cluster: 'research',
    name: 'Deep-Learning-Specialization',
    lang: 'Python',
    tagline: 'Comprehensive deep learning implementations and optimization experiments',
    summary: 'Practical implementations and optimization experiments from the Deep Learning Specialization. Covers deep neural networks, CNNs, sequence models, and machine learning project structuring, featuring vectorized gradient descent from scratch, custom Keras/TensorFlow architectures, and validation pipelines.',
    highlights: [
      'Built deep neural networks from scratch using vectorized NumPy',
      'Optimized hyperparameter tuning with Adam, RMSProp, and L1/L2 regularization',
      'Designed CNNs for image classification and spatial feature learning',
      'Implemented sequence models using RNNs, LSTMs, and GRUs for temporal data'
    ],
    tech: ['Python', 'TensorFlow', 'Keras', 'NumPy', 'Jupyter Notebook'],
    github: 'https://github.com/thippeswammy/Deep-Learning-Specialization',
    demo: '',
    docs: '',
    paper: '',
    isPrivate: false,
    status: 'completed',
    year: '',
    team: 'solo',
    platform: [],
    datasets: [],
    thumbnail: '',
    images: [],
    metrics: {}
  },

{
    id: 'kitti-odom-eval',
    cluster: 'research',
    name: 'kitti-odom-eval',
    lang: 'Python',
    tagline: 'KITTI Odometry Evaluation Toolbox',
    summary: 'An enhanced evaluation toolbox for the KITTI Odometry benchmark. Enables robust parsing of various pose formats (KITTI, TUM, with/without timestamps) and automatic timestamp alignment/normalization for accurate metric evaluation.',
    highlights: [
      'Robust Parsing of multiple pose formats',
      'Automatic Timestamp Normalization',
      'Driven by YAML configuration files',
      'Supports alignments like 7dof, 6dof, scale'
    ],
    tech: ['Python', 'NumPy', 'Pandas', 'Plotly', 'PyYAML', 'SciPy'],
    github: 'https://github.com/thippeswammy/kitti-odom-eval',
    demo: '',
    docs: '',
    paper: '',
    isPrivate: false,
    status: 'completed',
    year: '',
    team: 'solo',
    platform: [],
    datasets: ['KITTI'],
    thumbnail: '',
    images: [],
    metrics: {}
  }
];
