// ═══════════════════════════════════════════════════════════════════
// projects_data.js  —  Complete Project Portfolio Data
// ═══════════════════════════════════════════════════════════════════

window.CLUSTERS = [
  { id: 'vision', label: 'AI & CV', full: 'AI & Computer Vision', color: 0x3b82f6, css: '#3b82f6', emoji: '👁️' },
  { id: 'robotics', label: 'ROBOTICS', full: 'Robotics & Autonomous Systems', color: 0x06b6d4, css: '#06b6d4', emoji: '🤖' },
  { id: 'embedded', label: 'EMBEDDED', full: 'Embedded & Hardware', color: 0xf97316, css: '#0xf97316', emoji: '🔌' },
  { id: 'software', label: 'SOFTWARE', full: 'Desktop Applications', color: 0x10b981, css: '#0x10b981', emoji: '💻' },
  { id: 'mobile', label: 'MOBILE & AR', full: 'Mobile & Augmented Reality', color: 0x8b5cf6, css: '#0x8b5cf6', emoji: '📱' },
  { id: 'games', label: 'GAMES', full: 'Games & Interactive', color: 0xd946ef, css: '#0xd946ef', emoji: '🎮' },
  { id: 'research', label: 'RESEARCH', full: 'Research & Dev Tools', color: 0xec4899, css: '#0xec4899', emoji: '🔬' },
  { id: 'others', label: 'OTHERS', full: 'Miscellaneous & Sandbox', color: 0x64748b, css: '#0x64748b', emoji: '📂' },
];

window.PINNED_PROJECTS = [
  'autoseg',
  'jarviscontrolsystem',
  'lanemappingtool',
  'adas-for-indian-road-vehicle',
  'facerecognition',
  'mbd-dspace',
  'droid-slam',
];

window.PROJECTS = [
  // ── ROBOTICS ────────────────────────────────────────────────────────────────
  { id:'lanemappingtool', cluster:'robotics', name:'LaneMappingTool', lang:'Python',
    tagline:'Lane graph mapping for autonomous vehicles',
    summary:'Transforms noisy recorded vehicle paths into structured graph-based lane networks with B-spline smoothing, junction logic, and a React+Flask web UI.',
    highlights:['Graph-based lane network (nodes + edges)','B-Spline path smoothing','React + Vite frontend + Flask REST backend','Deploys to AV stack via .pickle export'],
    tech:['python','react','flask','chart.js','adas','autonomous-driving'],
    github:'https://github.com/thippeswammy/LaneMappingTool', isPrivate:false },

  { id:'my_bot', cluster:'robotics', name:'my_bot', lang:'Python',
    tagline:'Automated utility bot.',
    summary:'Sandbox for automation and scripting tests.',
    tech:['python','automation'],
    github:'https://github.com/thippeswammy/my_bot', isPrivate:false },

  { id:'3d_robot', cluster:'robotics', name:'3d_robot', lang:'C++',
    tagline:'3D Robot modeling and kinematic simulation.',
    summary:'Workspace for developing kinematic control logic and 3D robotic visualizations.',
    tech:['cpp','robotics'],
    github:'https://github.com/thippeswammy/3d_robot', isPrivate:false },

  { id:'sdf-to-nav-mesh', cluster:'robotics', name:'sdf_to_nav_mesh', lang:'Python',
    tagline:'SDF world → navigation mesh converter',
    summary:'ROS 2 tool converting Gazebo SDF/World files into .ply, .dae, .h5 navigation mesh assets with terrain metadata for autonomous navigation pipelines.',
    highlights:['Gazebo SDF → PLY/DAE/H5 pipeline','Terrain metadata extraction','ROS 2 native integration','Mesh-based AV navigation support'],
    tech:['python','ros2','gazebo','3d-geometry','autonomous-systems'],
    github:'https://github.com/thippeswammy/sdf_to_nav_mesh', isPrivate:false },

  { id:'rtab_ws', cluster:'robotics', name:'rtab_ws', lang:'C++',
    tagline:'RTAB-Map SLAM workspace',
    summary:'RGB-D SLAM workspace using RTAB-Map for 3D mapping with loop closure, ZED2i/RealSense support, and full ROS 2 integration.',
    highlights:['RGB-D 3D mapping with loop closure','ZED2i + RealSense support','ROS 2 package configuration','Trajectory evaluation tools'],
    tech:['cpp','ros2','python','slam'],
    github:'https://github.com/thippeswammy/rtab_ws', isPrivate:false },

  { id:'orb-slam2', cluster:'robotics', name:'ORB_SLAM2', lang:'C++',
    tagline:'Real-time visual SLAM for mono/stereo/RGB-D',
    summary:'Feature-based SLAM for monocular, stereo, and RGB-D cameras. Provides real-time trajectory reconstruction with loop closure and map reuse.',
    highlights:['Monocular, stereo & RGB-D support','ORB feature extraction + DBoW2 place recognition','Real-time loop closure & map reuse','Evaluated on TUM, KITTI, EuRoC datasets'],
    tech:['cpp','slam','computer-vision','opencv','eigen','g2o','dbow2'],
    github:'https://github.com/thippeswammy/ORB_SLAM2', isPrivate:false },

  { id:'orb-slam3', cluster:'robotics', name:'ORB_SLAM3', lang:'C++',
    tagline:'Multi-sensor visual-inertial SLAM (IEEE TRO 2021)',
    summary:'First real-time SLAM for Visual, Visual-Inertial and Multi-Map scenarios with monocular, stereo, RGB-D cameras. Supports fisheye and pinhole lenses.',
    highlights:['Monocular + Stereo + IMU fusion','Multi-map with seamless merging','Fisheye & pinhole lens models','IEEE Transactions on Robotics 2021'],
    tech:['cpp','slam','vins','eigen','dbow2','g2o','pangolin'],
    github:'https://github.com/thippeswammy/ORB_SLAM3', isPrivate:false },

  { id:'orb-slam3-ros2', cluster:'robotics', name:'ORB_SLAM3_ROS2', lang:'C++',
    tagline:'ORB-SLAM3 integration for the ROS 2 ecosystem.',
    summary:'Robust visual SLAM supporting Monocular, Stereo, and RGB-D cameras with IMU integration for real-time trajectory estimation.',
    tech:['cpp','ros2','slam','visual-odometry'],
    github:'https://github.com/thippeswammy/ORB_SLAM3_ROS2', isPrivate:false },

  { id:'droid-slam', cluster:'robotics', name:'DROID_SLAM', lang:'Python',
    tagline:'Deep visual SLAM with multi-GPU support',
    summary:'Deep learning SLAM extended for mono/stereo/RGB-D with multi-GPU inference and ARM64/Jetson support for real-time trajectory reconstruction.',
    highlights:['Monocular, stereo & RGB-D modes','Multi-GPU parallel inference','ARM64/Jetson Nano/AGX support','Real-time 3D trajectory visualization'],
    tech:['python','pytorch','cuda','ros','deep-learning','slam','jetson'],
    github:'https://github.com/thippeswammy/DROID_slam', isPrivate:false },

  { id:'dpvo', cluster:'robotics', name:'DPVO', lang:'C++',
    tagline:'Deep patch visual odometry',
    summary:'Lightweight deep visual odometry re-implementation with patch-based feature tracking for accurate, low-latency ego-motion estimation.',
    highlights:['Patch-based deep feature tracking','Low-latency odometry pipeline','Evaluated on EuRoC & TUM-RGBD','C++ & Python hybrid pipeline'],
    tech:['cpp','python','pytorch','visual-odometry'],
    github:'https://github.com/thippeswammy/DPVO', isPrivate:false },

  { id:'kitti-odom-eval', cluster:'robotics', name:'kitti-odom-eval', lang:'Python',
    tagline:'KITTI odometry trajectory benchmarking',
    summary:'Trajectory accuracy evaluation for VO/SLAM systems vs KITTI ground truth. Computes ATE & RPE metrics with multi-sequence batch support.',
    highlights:['ATE & RPE trajectory metrics','KITTI dataset format support','Trajectory error visualization','Multi-sequence batch evaluation'],
    tech:['python','slam','data-analysis','numpy','matplotlib'],
    github:'https://github.com/thippeswammy/kitti-odom-eval', isPrivate:false },

  // ── AI & COMPUTER VISION ────────────────────────────────────────────────────────────────
  { id:'jarviscontrolsystem', cluster:'vision', name:'JarvisControlSystem', lang:'Python',
    tagline:'J.A.R.V.I.S. AI autonomous desktop agent',
    summary:'Autonomous AI desktop agent for Windows. Uses local LLMs (Ollama), A* UI navigation, DAG memory model, Telegram remote control, and self-learning macros.',
    highlights:['LLM-powered intent recognition (Ollama)','A* pathfinding for UI state navigation','5-layer DAG persistent memory model','Telegram bot remote command interface'],
    tech:['python','ollama','llm','ai','autonomous-agent','automation'],
    github:'https://github.com/thippeswammy/JarvisControlSystem', isPrivate:false },

  { id:'autoseg', cluster:'vision', name:'AutoSegmentor', lang:'Python',
    tagline:'Auto-labeling ecosystem for AI datasets',
    summary:'Integrates Meta\'s SAM2 with CoTracker to convert raw videos into structured YOLO datasets with minimal human input. Features a PyQt5 GUI and async GPU processing.',
    highlights:['SAM2 real-time mask propagation','CoTracker for complex scene keypoints','Interactive PyQt5 GUI with zoom & undo','One-click YOLO v8/v11 dataset export with augmentation'],
    tech:['python','sam2','pytorch','pyqt5','cuda'],
    github:'https://github.com/thippeswammy/AutoSegmentor', isPrivate:false },

  { id:'adas-for-indian-road-vehicle', cluster:'vision', name:'ADAS-for-Indian-Road-Vehicle', lang:'Python',
    tagline:'ADAS for Indian road conditions with YOLOv8-Seg',
    summary:'ADAS using YOLOv8-Seg on 45,000+ annotated Indian road images. Achieves 95%+ accuracy at real-time inference with SLIC superpixel refinement.',
    highlights:['YOLOv8-Seg instance segmentation','45K+ annotated Indian road images','Mean IoU: 0.8983, Accuracy: 95.21%','SLIC superpixel boundary refinement'],
    tech:['python','yolov8','opencv','pytorch','adas','computer-vision'],
    github:'https://github.com/thippeswammy/ADAS-for-Indian-Road-Vehicle', isPrivate:false },

  { id:'facerecognition', cluster:'vision', name:'FaceRecognition', lang:'Python',
    tagline:'Dual-engine face recognition system',
    summary:'Two-mode face recognition: dynamic one-shot auto-tagging with depth sensing for new faces, and static YOLOv8 classification for secure known-face environments.',
    highlights:['One-shot learning for new face registration','YOLOv8 static classification engine','ZED2i depth sensing for liveness','Dual-mode: auto-tag vs secure mode'],
    tech:['python','yolov8','zed sdk','opencv','computer-vision','deep-learning','realsense'],
    github:'https://github.com/thippeswammy/FaceRecognition', isPrivate:false },

  { id:'supergluepretrainednetwork', cluster:'vision', name:'SuperGlueNetwork', lang:'Python',
    tagline:'Feature matching with Graph Neural Networks.',
    summary:'High-accuracy point matching in challenging lighting and perspective conditions.',
    tech:['pytorch','gnn','computer-vision'],
    github:'https://github.com/thippeswammy/SuperGluePretrainedNetwork', isPrivate:false },

  { id:'ros2-depth-anything-v3-trt', cluster:'vision', name:'ros2-depth-anything-v3-trt', lang:'C++',
    tagline:'TensorRT Monocular Depth estimation node.',
    summary:'Real-time metric depth and point cloud generation from single camera feeds using Depth Anything V3.',
    tech:['cpp','tensorrt','ros2','depth-estimation'],
    github:'https://github.com/thippeswammy/ros2-depth-anything-v3-trt', isPrivate:false },

  { id:'carla', cluster:'vision', name:'Carla', lang:'Python',
    tagline:'CARLA simulator for AV development',
    summary:'CARLA-based autonomous driving dev repo with traffic generation, scenario control, vehicle behavior testing, and perception experimentation.',
    highlights:['Traffic generation & NPC control','Ego-vehicle perception & control','Sensor suite simulation (cam, LiDAR, radar)','Python + C++ hybrid scripts'],
    tech:['python','cpp','carla','autonomous-driving','simulation'],
    github:'https://github.com/thippeswammy/Carla', isPrivate:false },

  { id:'zed2i', cluster:'vision', name:'ZED2i', lang:'Python',
    tagline:'Stereo vision & depth intelligence',
    summary:'ZED2i and RealSense D435i integration for synchronized multi-camera acquisition, Mask R-CNN depth estimation, and cm-level distance measurement.',
    highlights:['Synchronized ZED + RealSense recording','Mask R-CNN with Hungarian matching','High-frequency IMU logging','cm-level stereo depth accuracy'],
    tech:['python','zed sdk','pytorch','opencv','stereo-vision','depth-estimation','multithreading'],
    github:'https://github.com/thippeswammy/ZED2i', isPrivate:false },

  // ── EMBEDDED & HARDWARE ────────────────────────────────────────────────────────────────
  { id:'matlabmodels', cluster:'embedded', name:'MatlabModels', lang:'MATLAB',
    tagline:'MATLAB/Simulink automotive models',
    summary:'MATLAB and Simulink models for embedded automotive systems — sensor interfacing, behavioral modeling, and hardware integration with Arduino, RPi, STM32, and dSPACE.',
    highlights:['SIL/HIL workflow validation','Arduino/STM32/RPi hardware interfacing','Automotive behavioral modeling','CAN bus signal simulation in Simulink'],
    tech:['matlab','simulink','arduino','control-systems'],
    github:'https://github.com/thippeswammy/MatlabModels', isPrivate:false },

  { id:'mbd-dspace', cluster:'embedded', name:'MBD-dSPACE', lang:'MATLAB',
    tagline:'dSPACE SCALEXIO vehicle control HIL',
    summary:'dSPACE SCALEXIO-based vehicle control with MATLAB/Simulink. External signal loopback (no physical ECUs) for SIL and HIL workflow validation.',
    highlights:['External signal loopback (no physical ECU)','SIL + HIL behavioral comparison','dSPACE SCALEXIO rack integration','Simulink-to-hardware code generation'],
    tech:['matlab','simulink','dspace','automotive','embedded'],
    github:'https://github.com/thippeswammy/MBD-dSPACE', isPrivate:true },

  { id:'arduino', cluster:'embedded', name:'Arduino', lang:'C++',
    tagline:'Embedded systems project collection',
    summary:'Collection of Arduino projects: CAN bus communication, face tracking servos, obstacle avoidance vehicles, traffic control, and IoT water management.',
    highlights:['CAN bus with MCP2515 module','Face tracking servo control system','Ultrasonic obstacle avoidance car','IoT water management with ESP8266'],
    tech:['cpp','arduino','esp8266','can-bus','iot'],
    github:'https://github.com/thippeswammy/Arduino', isPrivate:false },

  { id:'eceproject', cluster:'embedded', name:'EceProject', lang:'Python',
    tagline:'ECE engineering workspace',
    summary:'Integrated ECE workspace covering computer vision, embedded systems, and robotics with Arduino control, stereo camera processing, and IoT on ESP8266/RPi.',
    highlights:['Stereo camera processing pipeline','Arduino + ESP8266 IoT integration','Rapid prototyping experiments','Computer vision with Raspberry Pi'],
    tech:['python','cpp','arduino'],
    github:'https://github.com/thippeswammy/EceProject', isPrivate:false },

  // ── SOFTWARE (DESKTOP APPLICATIONS) ────────────────────────────────────────────────────────────────
  { id:'secureapplocker', cluster:'software', name:'SecureAppLocker', lang:'Java',
    tagline:'Secure application launcher with login authentication.',
    summary:'Java-based tool restricting access to protected applications through system-level validation.',
    tech:['java','swing','security'],
    github:'https://github.com/thippeswammy/SecureAppLocker', isPrivate:false },

  { id:'loginsystemwithadvancegui', cluster:'software', name:'LoginSystemAdvanced', lang:'Java',
    tagline:'Advanced Java authentication system',
    summary:'Java Swing authentication system with structured login/registration workflows, modular GUI design, real-time input validation, and event-driven architecture.',
    highlights:['Modular login/registration workflow','Real-time input validation feedback','Event-driven programming pattern','Scalable desktop GUI architecture'],
    tech:['java','swing','gui-design'],
    github:'https://github.com/thippeswammy/LoginSystemWithAdvanceGUI', isPrivate:false },

  { id:'loginsystemwithgui', cluster:'software', name:'LoginSystemBasic', lang:'Java',
    tagline:'Standard Java authentication system.',
    summary:'Implements user login logic and event-driven interaction for desktop applications.',
    tech:['java','swing','authentication'],
    github:'https://github.com/thippeswammy/LoginSystemWithGUI', isPrivate:false },

  { id:'simplecontactsmanager', cluster:'software', name:'SimpleContactsManager', lang:'Java',
    tagline:'Desktop contact and messaging management system.',
    summary:'Console/GUI hybrid for CRUD operations on personal records and messages.',
    tech:['java','data-management','desktop-app'],
    github:'https://github.com/thippeswammy/SimpleContactsManager', isPrivate:false },

  { id:'multiapprunnerloginauth', cluster:'software', name:'MultiAppRunner', lang:'Java',
    tagline:'Authenticated central hub for launching multiple Java tools.',
    summary:'Access control layer for a suite of desktop tools and games.',
    tech:['java','authentication','launcher'],
    github:'https://github.com/thippeswammy/MultiAppRunnerLoginAuth', isPrivate:false },

  { id:'calculatorguiapp', cluster:'software', name:'CalculatorGUI', lang:'Java',
    tagline:'Feature-rich desktop calculator with modular logic.',
    summary:'Built with NetBeans, supporting complex arithmetic with reusable backend logic.',
    tech:['java','swing','calculator'],
    github:'https://github.com/thippeswammy/CalculatorGuiApp', isPrivate:false },

  { id:'basicmathcalculatorapp', cluster:'software', name:'BasicCalculator', lang:'Java',
    tagline:'Lightweight arithmetic desktop tool.',
    summary:'Focuses on simple input handling and arithmetic logic execution.',
    tech:['java','swing','beginner-project'],
    github:'https://github.com/thippeswammy/BasicMathCalculatorApp', isPrivate:false },

  // ── MOBILE & AR ────────────────────────────────────────────────────────────────
  { id:'ar-cube-drop', cluster:'mobile', name:'AR-Cube-Drop', lang:'C#',
    tagline:'AR cube placement with ARFoundation',
    summary:'Unity ARFoundation app for interactive cube placement with real-time ARCore plane detection, object spawning, and automated scene capture.',
    highlights:['ARFoundation plane detection','Interactive object spawning on surfaces','Automated scene capture system','Real-time AR rendering pipeline'],
    tech:['unity','csharp','arfoundation','augmented-reality'],
    github:'https://github.com/thippeswammy/AR-Cube-Drop', isPrivate:false },

  { id:'speechcalculator', cluster:'mobile', name:'SpeechCalculator', lang:'Java',
    tagline:'Voice-enabled math calculator for Android',
    summary:'Android calculator using speech recognition to parse spoken math expressions with a custom priority-based expression evaluator and voice feedback.',
    highlights:['Android SpeechRecognizer API integration','Custom expression tokenizer & parser','Operator precedence evaluation engine','Voice feedback for calculation results'],
    tech:['android','java','speech-recognition'],
    github:'https://github.com/thippeswammy/SpeechCalculator', isPrivate:false },

  { id:'roadtagbycameragps', cluster:'mobile', name:'RoadTagByCameraGps', lang:'Kotlin',
    tagline:'GPS-tagged road imagery collection',
    summary:'Android app for collecting GPS-tagged road imagery, synchronizing camera and GPS data for road annotation and mapping workflows.',
    highlights:['Synchronized camera + GPS capture','Geotagged image metadata embedding','Background location tracking service','CSV/JSON export for mapping tools'],
    tech:['kotlin','android','gps','infrastructure'],
    github:'https://github.com/thippeswammy/RoadTagByCameraGps', isPrivate:true },

  { id:'smartparking', cluster:'mobile', name:'SmartCarParkingSystem', lang:'Java',
    tagline:'Real-time smart parking Android app',
    summary:'Android smart parking app with Firebase Firestore real-time updates, Google Maps navigation, IoT sensor integration, and payment gateway.',
    highlights:['Firebase Firestore real-time slot updates','Google Maps navigation integration','Razorpay/Stripe payment gateway','IoT sensor + AI camera slot detection'],
    tech:['android','java','firebase','google maps'],
    github:'https://github.com/thippeswammy/SmartParking', isPrivate:true },

  // ── GAMES ────────────────────────────────────────────────────────────────
  { id:'3d-car-racing-game', cluster:'games', name:'CarRacingUnity', lang:'C#',
    tagline:'3D car racing game in Unity',
    summary:'Unity 3D car racing with multiple vehicles, dynamic environments, real-time navigation guidance, and 3D spatial sound system.',
    highlights:['Multiple playable vehicle models','Dynamic race track environment','Real-time navigation guidance','3D spatial sound system'],
    tech:['unity','csharp','3d-graphics'],
    github:'https://github.com/thippeswammy/3D-Car-racing-game', isPrivate:false },

  { id:'chainreactiongame', cluster:'games', name:'ChainReaction', lang:'Java',
    tagline:'Grid-based multiplayer chain reaction strategy',
    summary:'Java Greenfoot chain-reaction strategy game with turn-based gameplay, chain propagation logic, and multi-player territory capture mechanics.',
    highlights:['Chain-reaction propagation algorithm','Turn-based multi-player mechanics','Grid state management','Strategic territory capture gameplay'],
    tech:['java','greenfoot','algorithms'],
    github:'https://github.com/thippeswammy/ChainReactionGame', isPrivate:false },

  { id:'puzzle-game', cluster:'games', name:'Puzzle-game', lang:'Java',
    tagline:'Number puzzle from 3×3 to 6×6',
    summary:'Java Swing sliding number puzzle supporting 3×3 to 6×6 grids with randomized solvable initialization, move validation, and animated tile transitions.',
    highlights:['Dynamic grid sizes (3×3 to 6×6)','Randomized solvable initialization','Move validation & state tracking','Animated tile transitions'],
    tech:['java','swing','algorithms'],
    github:'https://github.com/thippeswammy/Puzzle-game', isPrivate:false },

  { id:'maze-game', cluster:'games', name:'MazeSurvival', lang:'Java',
    tagline:'Maze with enemy AI & level progression',
    summary:'Greenfoot maze game with enemy AI behaviors, collision handling, speed boosts, and level progression demonstrating 2D game design and OOP principles.',
    highlights:['Enemy AI with pathfinding behavior','Collision detection system','Speed boost power-ups','Multi-level progression system'],
    tech:['java','greenfoot','game-ai'],
    github:'https://github.com/thippeswammy/Maze-game', isPrivate:false },

  { id:'snake-gui-game', cluster:'games', name:'SnakeGUI', lang:'Java',
    tagline:'Classic Snake with real-time game loop',
    summary:'Java Swing Snake with custom rendering, real-time game loop, collision detection, and smooth animation — demonstrating event-driven desktop app design.',
    highlights:['Custom rendering with Java Graphics2D','Real-time game loop with thread timing','Collision detection with walls & self','Score tracking and difficulty scaling'],
    tech:['java','swing','game-loop'],
    github:'https://github.com/thippeswammy/Snake-GUI-game', isPrivate:false },

  { id:'tictactoegui', cluster:'games', name:'TicTacToeAI', lang:'Java',
    tagline:'Tic Tac Toe with AI opponent',
    summary:'Java Swing Tic Tac Toe with a strategy-driven AI using minimax game state evaluation, win-condition logic, and animated interactive GUI.',
    highlights:['AI with minimax strategy logic','Win-condition detection for all patterns','Event-driven programming architecture','Clean GUI with animated feedback'],
    tech:['java','swing','game-logic'],
    github:'https://github.com/thippeswammy/TicTacToeGUI', isPrivate:false },

  { id:'supermariogame', cluster:'games', name:'MarioClone', lang:'Java',
    tagline:'Classic arcade mechanics in Greenfoot.',
    summary:'Focuses on obstacle navigation and smooth 2D gameplay physics.',
    tech:['java','greenfoot','2d-game'],
    github:'https://github.com/thippeswammy/SuperMarioGame', isPrivate:false },

  { id:'brickgame', cluster:'games', name:'BrickBreaker', lang:'Java',
    tagline:'Physics-based 2D brick destruction game.',
    summary:'Features ball physics and paddle control interaction.',
    tech:['java','greenfoot','physics'],
    github:'https://github.com/thippeswammy/BrickGame', isPrivate:false },

  { id:'flappy-bird-game', cluster:'games', name:'FlappyBird', lang:'Java',
    tagline:'Classic Flappy Bird clone',
    summary:'Java Greenfoot Flappy Bird with physics-based bird movement, procedurally generated pipes, score tracking, and smooth frame-rate animation.',
    highlights:['Physics-based bird movement','Procedurally generated pipe obstacles','Score tracking & high score','Smooth animation at fixed frame rate'],
    tech:['java','greenfoot'],
    github:'https://github.com/thippeswammy/Flappy-bird-game', isPrivate:false },

  { id:'ballonblastgame', cluster:'games', name:'BalloonBlast', lang:'Java',
    tagline:'2D projectile shooting game.',
    summary:'Interactive gameplay with multiple targets and scoring systems.',
    tech:['java','greenfoot'],
    github:'https://github.com/thippeswammy/BallonBlastGame', isPrivate:false },

  { id:'downshootergame', cluster:'games', name:'TopDownShooter', lang:'Java',
    tagline:'2D top-down shooter with boss battles',
    summary:'Java Greenfoot top-down shooter with enemy AI movement patterns, multi-stage boss battles, health system, and score-based difficulty scaling.',
    highlights:['Enemy AI with movement patterns','Multi-stage boss battles','Health & shield system','Score-based difficulty scaling'],
    tech:['java','greenfoot'],
    github:'https://github.com/thippeswammy/DownShooterGame', isPrivate:false },

  { id:'handcricketgame', cluster:'games', name:'HandCricket', lang:'Java',
    tagline:'Digital simulation of the classic school game.',
    summary:'Uses user-input driven mechanics and score tracking logic.',
    tech:['java','console-app','game-logic'],
    github:'https://github.com/thippeswammy/HandCricketGame', isPrivate:false },

  { id:'textbasedtictactoe', cluster:'games', name:'TextTicTacToe', lang:'Java',
    tagline:'Console-based strategy game.',
    summary:'Includes AI modes and difficulty levels without a GUI.',
    tech:['java','console-app'],
    github:'https://github.com/thippeswammy/TextBasedTicTacToe', isPrivate:false },

  { id:'numberguessergame', cluster:'games', name:'NumberGuesser', lang:'Java',
    tagline:'AI-driven number guessing challenge.',
    summary:'Interactive competitive logic with multiple difficulty levels.',
    tech:['java','console-app'],
    github:'https://github.com/thippeswammy/NumberGuesserGame', isPrivate:false },

  // ── RESEARCH & LEARNING ────────────────────────────────────────────────────────────────
  { id:'deep-learning-specialization', cluster:'research', name:'DL-Specialization', lang:'Python',
    tagline:'Coursera Deep Learning Specialization',
    summary:'Coursera DL Specialization assignments — neural networks, CNNs, RNNs, optimization algorithms, and practical deep learning applications across 5 courses.',
    highlights:['5-course DL specialization exercises','CNN architectures (ResNet, VGG, Inception)','Sequence models & attention mechanism','Hyperparameter tuning & optimization'],
    tech:['python','tensorflow','numpy','deep-learning','neural-networks'],
    github:'https://github.com/thippeswammy/Deep-Learning-Specialization', isPrivate:false },

  { id:'imageprocessingcourse', cluster:'research', name:'ImageProcessing', lang:'Python',
    tagline:'Core image processing techniques',
    summary:'Implementations of fundamental image processing from the Duke/Coursera course — filtering, transforms, morphology, edge detection and analysis.',
    highlights:['Spatial & frequency domain filtering','Geometric transformations','Morphological operations','Edge detection & segmentation algorithms'],
    tech:['python','opencv','numpy','scipy','computer-vision'],
    github:'https://github.com/thippeswammy/ImageProcessingCourse', isPrivate:false },

  { id:'neetcodeproblems', cluster:'research', name:'NeetCodeProblems', lang:'Java',
    tagline:'NeetCode 150 algorithm solutions in Java',
    summary:'Java solutions to NeetCode 150 roadmap problems — arrays, graphs, DP, trees, and system design — structured for interview preparation.',
    highlights:['NeetCode 150 roadmap coverage','Graph, DP & tree algorithm solutions','Time/space complexity documentation','Clean OOP Java implementation style'],
    tech:['java','dsa','algorithms'],
    github:'https://github.com/thippeswammy/NeetCodeProblems', isPrivate:false },

  { id:'vo2map', cluster:'research', name:'VO2MAP', lang:'HTML',
    tagline:'Research on Visual Odometry to Map registration.',
    summary:'Theoretical workspace for mapping VO data onto global maps.',
    tech:['mapping','slam','research'],
    github:'https://github.com/thippeswammy/VO2MAP', isPrivate:false },

  { id:'multiplevo', cluster:'research', name:'MultipleVo', lang:'HTML',
    tagline:'Comparative analysis of multiple VO algorithms.',
    summary:'Sandbox for evaluating performance across different odometry implementations.',
    tech:['visual-odometry','computer-vision'],
    github:'https://github.com/thippeswammy/MultipleVo', isPrivate:false },


  // ── OTHERS ────────────────────────────────────────────────────────────────

  { id:'thippeswammy.github.io', cluster:'others', name:'Portfolio Website', lang:'HTML',
    tagline:'My technical portfolio and project showcase.',
    summary:'The very site you are viewing, built for responsive project discovery.',
    tech:['html','css','javascript'],
    github:'https://github.com/thippeswammy/thippeswammy.github.io', isPrivate:false },

  { id:'my_mcp_project', cluster:'others', name:'my_mcp_project', lang:'Python',
    tagline:'Model Context Protocol (MCP) tooling',
    summary:'MCP server implementation for integrating local tools and resources with LLM backends for AI agent workflows with extensible plugin architecture.',
    highlights:['MCP server implementation','Tool & resource provider integration','LLM context management pipeline','Extensible plugin architecture'],
    tech:['python','mcp','ai-agents'],
    github:'https://github.com/thippeswammy/my_mcp_project', isPrivate:false },

  { id:'rosrec', cluster:'others', name:'ROSDataRecorder', lang:'Python',
    tagline:'ROS multi-sensor data recording & comparison',
    summary:'Synchronized ROS sensor data recording tool with playback and comparison analysis for validating SLAM, odometry, and perception pipelines.',
    highlights:['Multi-sensor synchronized recording','Rosbag playback & comparison tools','Trajectory & sensor data overlay','Automated quality metric reporting'],
    tech:['python','ros','ros 2'],
    github:'https://github.com/thippeswammy/ROSDataRecorderandComparisonWalkthrough', isPrivate:true },

  { id:'dataviz', cluster:'others', name:'DataVisualizationEditingTool', lang:'Python',
    tagline:'Interactive sensor data visualization editor',
    summary:'Custom Python tool for editing, annotating, and visualizing sensor data and trajectory datasets with interactive plotting and export capabilities.',
    highlights:['Interactive plot annotation & editing','Multi-dataset overlay visualization','Custom color mapping & filtering','CSV/NumPy data export pipeline'],
    tech:['python','matplotlib','numpy'],
    github:'https://github.com/thippeswammy/DataVisualizationEditingTool', isPrivate:true },

  { id:'lidar', cluster:'others', name:'LidarScanSegment', lang:'Python',
    tagline:'LiDAR point cloud scan segmentation',
    summary:'Python LiDAR scan segmentation tool for autonomous vehicle perception — ground removal, Euclidean cluster extraction, and label export.',
    highlights:['Ground plane removal (RANSAC)','Euclidean cluster extraction','Scan-level label assignment','ROS bag & PCL file input support'],
    tech:['python','pcl','ros'],
    github:'https://github.com/thippeswammy/LidarScanSegment', isPrivate:true },

];