// ═══════════════════════════════════════════════════════════════════
// projects_data.js  —  Edit project info here, independent of UI
// ═══════════════════════════════════════════════════════════════════

window.CLUSTERS = [
  { id:'robotics', label:'ROBOTICS',     full:'Robotics & Autonomous Systems', color:0x06b6d4, css:'#06b6d4', emoji:'🤖' },
  { id:'ai',       label:'AI & CV',       full:'AI & Computer Vision',           color:0x3b82f6, css:'#3b82f6', emoji:'🧠' },
  { id:'games',    label:'GAMES',         full:'Games',                           color:0xa855f7, css:'#a855f7', emoji:'🎮' },
  { id:'embedded', label:'EMBEDDED',      full:'Embedded & Hardware',             color:0xf97316, css:'#f97316', emoji:'⚡' },
  { id:'apps',     label:'APPS',          full:'Apps & Software',                 color:0x22c55e, css:'#22c55e', emoji:'📱' },
  { id:'tools',    label:'DEV TOOLS',     full:'Dev Tools & Research',            color:0xec4899, css:'#ec4899', emoji:'🔧' },
];

window.PROJECTS = [
  // ── ROBOTICS ────────────────────────────────────────────────────────────────
  { id:'orbslam2', cluster:'robotics', name:'ORB_SLAM2', lang:'C++',
    tagline:'Real-time visual SLAM for mono/stereo/RGB-D',
    summary:'Feature-based SLAM for monocular, stereo, and RGB-D cameras. Provides real-time trajectory reconstruction with loop closure and map reuse.',
    highlights:['Monocular, stereo & RGB-D support','ORB feature extraction + DBoW2 place recognition','Real-time loop closure & map reuse','Evaluated on TUM, KITTI, EuRoC datasets'],
    tech:['C++','OpenCV','Eigen','g2o','DBoW2'],
    github:'https://github.com/thippeswammy/ORB_SLAM2', isPrivate:false },

  { id:'orbslam3', cluster:'robotics', name:'ORB_SLAM3', lang:'C++',
    tagline:'Multi-sensor visual-inertial SLAM (IEEE TRO 2021)',
    summary:'First real-time SLAM for Visual, Visual-Inertial and Multi-Map scenarios with monocular, stereo, RGB-D cameras. Supports fisheye and pinhole lenses.',
    highlights:['Monocular + Stereo + IMU fusion','Multi-map with seamless merging','Fisheye & pinhole lens models','IEEE Transactions on Robotics 2021'],
    tech:['C++','Eigen','DBoW2','g2o','Pangolin'],
    github:'https://github.com/thippeswammy/ORB_SLAM3', isPrivate:false },

  { id:'droid', cluster:'robotics', name:'DROID_SLAM', lang:'Python',
    tagline:'Deep visual SLAM with multi-GPU support',
    summary:'Deep learning SLAM extended for mono/stereo/RGB-D with multi-GPU inference and ARM64/Jetson support for real-time trajectory reconstruction.',
    highlights:['Monocular, stereo & RGB-D modes','Multi-GPU parallel inference','ARM64/Jetson Nano/AGX support','Real-time 3D trajectory visualization'],
    tech:['Python','PyTorch','CUDA','ROS'],
    github:'https://github.com/thippeswammy/DROID_slam', isPrivate:false },

  { id:'dpvo', cluster:'robotics', name:'DPVO', lang:'C++',
    tagline:'Deep patch visual odometry',
    summary:'Lightweight deep visual odometry re-implementation with patch-based feature tracking for accurate, low-latency ego-motion estimation.',
    highlights:['Patch-based deep feature tracking','Low-latency odometry pipeline','Evaluated on EuRoC & TUM-RGBD','C++ & Python hybrid pipeline'],
    tech:['C++','Python','PyTorch'],
    github:'https://github.com/thippeswammy/DPVO', isPrivate:false },

  { id:'lanemapping', cluster:'robotics', name:'LaneMappingTool', lang:'Python',
    tagline:'Lane graph mapping for autonomous vehicles',
    summary:'Transforms noisy recorded vehicle paths into structured graph-based lane networks with B-spline smoothing, junction logic, and a React+Flask web UI.',
    highlights:['Graph-based lane network (nodes + edges)','B-Spline path smoothing','React + Vite frontend + Flask REST backend','Deploys to AV stack via .pickle export'],
    tech:['Python','React','Flask','Chart.js'],
    github:'https://github.com/thippeswammy/LaneMappingTool', isPrivate:false },

  { id:'zed2i', cluster:'robotics', name:'ZED2i', lang:'Python',
    tagline:'Stereo vision & depth intelligence',
    summary:'ZED2i and RealSense D435i integration for synchronized multi-camera acquisition, Mask R-CNN depth estimation, and cm-level distance measurement.',
    highlights:['Synchronized ZED + RealSense recording','Mask R-CNN with Hungarian matching','High-frequency IMU logging','cm-level stereo depth accuracy'],
    tech:['Python','ZED SDK','PyTorch','OpenCV'],
    github:'https://github.com/thippeswammy/ZED2i', isPrivate:false },

  { id:'carla', cluster:'robotics', name:'Carla', lang:'Python',
    tagline:'CARLA simulator for AV development',
    summary:'CARLA-based autonomous driving dev repo with traffic generation, scenario control, vehicle behavior testing, and perception experimentation.',
    highlights:['Traffic generation & NPC control','Ego-vehicle perception & control','Sensor suite simulation (cam, LiDAR, radar)','Python + C++ hybrid scripts'],
    tech:['Python','C++','CARLA'],
    github:'https://github.com/thippeswammy/Carla', isPrivate:false },

  { id:'sdf2nav', cluster:'robotics', name:'sdf_to_nav_mesh', lang:'Python',
    tagline:'SDF world → navigation mesh converter',
    summary:'ROS 2 tool converting Gazebo SDF/World files into .ply, .dae, .h5 navigation mesh assets with terrain metadata for autonomous navigation pipelines.',
    highlights:['Gazebo SDF → PLY/DAE/H5 pipeline','Terrain metadata extraction','ROS 2 native integration','Mesh-based AV navigation support'],
    tech:['Python','ROS 2','Gazebo'],
    github:'https://github.com/thippeswammy/sdf_to_nav_mesh', isPrivate:false },

  { id:'rtab', cluster:'robotics', name:'rtab_ws', lang:'C++',
    tagline:'RTAB-Map SLAM workspace',
    summary:'RGB-D SLAM workspace using RTAB-Map for 3D mapping with loop closure, ZED2i/RealSense support, and full ROS 2 integration.',
    highlights:['RGB-D 3D mapping with loop closure','ZED2i + RealSense support','ROS 2 package configuration','Trajectory evaluation tools'],
    tech:['C++','ROS 2','Python'],
    github:'https://github.com/thippeswammy/rtab_ws', isPrivate:false },

  { id:'kittieval', cluster:'robotics', name:'kitti-odom-eval', lang:'Python',
    tagline:'KITTI odometry trajectory benchmarking',
    summary:'Trajectory accuracy evaluation for VO/SLAM systems vs KITTI ground truth. Computes ATE & RPE metrics with multi-sequence batch support.',
    highlights:['ATE & RPE trajectory metrics','KITTI dataset format support','Trajectory error visualization','Multi-sequence batch evaluation'],
    tech:['Python','NumPy','Matplotlib'],
    github:'https://github.com/thippeswammy/kitti-odom-eval', isPrivate:false },

  // ── AI & COMPUTER VISION ────────────────────────────────────────────────────
  { id:'autoseg', cluster:'ai', name:'AutoSegmentor', lang:'Python',
    tagline:'Auto-labeling ecosystem for AI datasets',
    summary:'Integrates Meta\'s SAM2 with CoTracker to convert raw videos into structured YOLO datasets with minimal human input. Features a PyQt5 GUI and async GPU processing.',
    highlights:['SAM2 real-time mask propagation','CoTracker for complex scene keypoints','Interactive PyQt5 GUI with zoom & undo','One-click YOLO v8/v11 dataset export with augmentation'],
    tech:['Python','SAM2','PyTorch','PyQt5','CUDA'],
    github:'https://github.com/thippeswammy/AutoSegmentor', isPrivate:false },

  { id:'adas', cluster:'ai', name:'ADAS-for-Indian-Road-Vehicle', lang:'Python',
    tagline:'ADAS for Indian road conditions with YOLOv8-Seg',
    summary:'ADAS using YOLOv8-Seg on 45,000+ annotated Indian road images. Achieves 95%+ accuracy at real-time inference with SLIC superpixel refinement.',
    highlights:['YOLOv8-Seg instance segmentation','45K+ annotated Indian road images','Mean IoU: 0.8983, Accuracy: 95.21%','SLIC superpixel boundary refinement'],
    tech:['Python','YOLOv8','OpenCV','PyTorch'],
    github:'https://github.com/thippeswammy/ADAS-for-Indian-Road-Vehicle', isPrivate:false },

  { id:'facerec', cluster:'ai', name:'FaceRecognition', lang:'Python',
    tagline:'Dual-engine face recognition system',
    summary:'Two-mode face recognition: dynamic one-shot auto-tagging with depth sensing for new faces, and static YOLOv8 classification for secure known-face environments.',
    highlights:['One-shot learning for new face registration','YOLOv8 static classification engine','ZED2i depth sensing for liveness','Dual-mode: auto-tag vs secure mode'],
    tech:['Python','YOLOv8','ZED SDK','OpenCV'],
    github:'https://github.com/thippeswammy/FaceRecognition', isPrivate:false },

  { id:'imgproc', cluster:'ai', name:'ImageProcessingCourse', lang:'Python',
    tagline:'Core image processing techniques',
    summary:'Implementations of fundamental image processing from the Duke/Coursera course — filtering, transforms, morphology, edge detection and analysis.',
    highlights:['Spatial & frequency domain filtering','Geometric transformations','Morphological operations','Edge detection & segmentation algorithms'],
    tech:['Python','OpenCV','NumPy','SciPy'],
    github:'https://github.com/thippeswammy/ImageProcessingCourse', isPrivate:false },

  { id:'deeplearn', cluster:'ai', name:'Deep-Learning-Specialization', lang:'Python',
    tagline:'Coursera Deep Learning Specialization',
    summary:'Coursera DL Specialization assignments — neural networks, CNNs, RNNs, optimization algorithms, and practical deep learning applications across 5 courses.',
    highlights:['5-course DL specialization exercises','CNN architectures (ResNet, VGG, Inception)','Sequence models & attention mechanism','Hyperparameter tuning & optimization'],
    tech:['Python','TensorFlow','NumPy'],
    github:'https://github.com/thippeswammy/Deep-Learning-Specialization', isPrivate:false },

  // ── GAMES ───────────────────────────────────────────────────────────────────
  { id:'snake', cluster:'games', name:'Snake-GUI-game', lang:'Java',
    tagline:'Classic Snake with real-time game loop',
    summary:'Java Swing Snake with custom rendering, real-time game loop, collision detection, and smooth animation — demonstrating event-driven desktop app design.',
    highlights:['Custom rendering with Java Graphics2D','Real-time game loop with thread timing','Collision detection with walls & self','Score tracking and difficulty scaling'],
    tech:['Java','Swing'],
    github:'https://github.com/thippeswammy/Snake-GUI-game', isPrivate:false },

  { id:'tictacgui', cluster:'games', name:'TicTacToeGUI', lang:'Java',
    tagline:'Tic Tac Toe with AI opponent',
    summary:'Java Swing Tic Tac Toe with a strategy-driven AI using minimax game state evaluation, win-condition logic, and animated interactive GUI.',
    highlights:['AI with minimax strategy logic','Win-condition detection for all patterns','Event-driven programming architecture','Clean GUI with animated feedback'],
    tech:['Java','Swing'],
    github:'https://github.com/thippeswammy/TicTacToeGUI', isPrivate:false },

  { id:'puzzle', cluster:'games', name:'Puzzle-game', lang:'Java',
    tagline:'Number puzzle from 3×3 to 6×6',
    summary:'Java Swing sliding number puzzle supporting 3×3 to 6×6 grids with randomized solvable initialization, move validation, and animated tile transitions.',
    highlights:['Dynamic grid sizes (3×3 to 6×6)','Randomized solvable initialization','Move validation & state tracking','Animated tile transitions'],
    tech:['Java','Swing'],
    github:'https://github.com/thippeswammy/Puzzle-game', isPrivate:false },

  { id:'maze', cluster:'games', name:'Maze-game', lang:'Java',
    tagline:'Maze with enemy AI & level progression',
    summary:'Greenfoot maze game with enemy AI behaviors, collision handling, speed boosts, and level progression demonstrating 2D game design and OOP principles.',
    highlights:['Enemy AI with pathfinding behavior','Collision detection system','Speed boost power-ups','Multi-level progression system'],
    tech:['Java','Greenfoot'],
    github:'https://github.com/thippeswammy/Maze-game', isPrivate:false },

  { id:'flappy', cluster:'games', name:'Flappy-bird-game', lang:'Java',
    tagline:'Classic Flappy Bird clone',
    summary:'Java Greenfoot Flappy Bird with physics-based bird movement, procedurally generated pipes, score tracking, and smooth frame-rate animation.',
    highlights:['Physics-based bird movement','Procedurally generated pipe obstacles','Score tracking & high score','Smooth animation at fixed frame rate'],
    tech:['Java','Greenfoot'],
    github:'https://github.com/thippeswammy/Flappy-bird-game', isPrivate:false },

  { id:'shooter', cluster:'games', name:'DownShooterGame', lang:'Java',
    tagline:'2D top-down shooter with boss battles',
    summary:'Java Greenfoot top-down shooter with enemy AI movement patterns, multi-stage boss battles, health system, and score-based difficulty scaling.',
    highlights:['Enemy AI with movement patterns','Multi-stage boss battles','Health & shield system','Score-based difficulty scaling'],
    tech:['Java','Greenfoot'],
    github:'https://github.com/thippeswammy/DownShooterGame', isPrivate:false },

  { id:'chain', cluster:'games', name:'ChainReactionGame', lang:'Java',
    tagline:'Grid-based multiplayer chain reaction strategy',
    summary:'Java Greenfoot chain-reaction strategy game with turn-based gameplay, chain propagation logic, and multi-player territory capture mechanics.',
    highlights:['Chain-reaction propagation algorithm','Turn-based multi-player mechanics','Grid state management','Strategic territory capture gameplay'],
    tech:['Java','Greenfoot'],
    github:'https://github.com/thippeswammy/ChainReactionGame', isPrivate:false },

  { id:'carracer', cluster:'games', name:'CarRacingUnity', lang:'C#',
    tagline:'3D car racing game in Unity',
    summary:'Unity 3D car racing with multiple vehicles, dynamic environments, real-time navigation guidance, and 3D spatial sound system.',
    highlights:['Multiple playable vehicle models','Dynamic race track environment','Real-time navigation guidance','3D spatial sound system'],
    tech:['Unity','C#'],
    github:'https://github.com/thippeswammy/3D-Car-racing-game', isPrivate:false },

  { id:'arcube', cluster:'games', name:'AR-Cube-Drop', lang:'C#',
    tagline:'AR cube placement with ARFoundation',
    summary:'Unity ARFoundation app for interactive cube placement with real-time ARCore plane detection, object spawning, and automated scene capture.',
    highlights:['ARFoundation plane detection','Interactive object spawning on surfaces','Automated scene capture system','Real-time AR rendering pipeline'],
    tech:['Unity','C#','ARFoundation'],
    github:'https://github.com/thippeswammy/AR-Cube-Drop', isPrivate:false },

  // ── EMBEDDED & HARDWARE ─────────────────────────────────────────────────────
  { id:'arduino', cluster:'embedded', name:'Arduino', lang:'C++',
    tagline:'Embedded systems project collection',
    summary:'Collection of Arduino projects: CAN bus communication, face tracking servos, obstacle avoidance vehicles, traffic control, and IoT water management.',
    highlights:['CAN bus with MCP2515 module','Face tracking servo control system','Ultrasonic obstacle avoidance car','IoT water management with ESP8266'],
    tech:['C++','Arduino','ESP8266'],
    github:'https://github.com/thippeswammy/Arduino', isPrivate:false },

  { id:'matlab', cluster:'embedded', name:'MatlabModels', lang:'MATLAB',
    tagline:'MATLAB/Simulink automotive models',
    summary:'MATLAB and Simulink models for embedded automotive systems — sensor interfacing, behavioral modeling, and hardware integration with Arduino, RPi, STM32, and dSPACE.',
    highlights:['SIL/HIL workflow validation','Arduino/STM32/RPi hardware interfacing','Automotive behavioral modeling','CAN bus signal simulation in Simulink'],
    tech:['MATLAB','Simulink','dSPACE'],
    github:'https://github.com/thippeswammy/MatlabModels', isPrivate:false },

  { id:'dspace', cluster:'embedded', name:'MBD-dSPACE', lang:'MATLAB',
    tagline:'dSPACE SCALEXIO vehicle control HIL',
    summary:'dSPACE SCALEXIO-based vehicle control with MATLAB/Simulink. External signal loopback (no physical ECUs) for SIL and HIL workflow validation.',
    highlights:['External signal loopback (no physical ECU)','SIL + HIL behavioral comparison','dSPACE SCALEXIO rack integration','Simulink-to-hardware code generation'],
    tech:['MATLAB','Simulink','dSPACE'],
    github:'https://github.com/thippeswammy/MBD-dSPACE', isPrivate:true },

  { id:'ece', cluster:'embedded', name:'EceProject', lang:'Python',
    tagline:'ECE engineering workspace',
    summary:'Integrated ECE workspace covering computer vision, embedded systems, and robotics with Arduino control, stereo camera processing, and IoT on ESP8266/RPi.',
    highlights:['Stereo camera processing pipeline','Arduino + ESP8266 IoT integration','Rapid prototyping experiments','Computer vision with Raspberry Pi'],
    tech:['Python','C++','Arduino'],
    github:'https://github.com/thippeswammy/EceProject', isPrivate:false },

  // ── APPS & SOFTWARE ─────────────────────────────────────────────────────────
  { id:'jarvis', cluster:'apps', name:'JarvisControlSystem', lang:'Python',
    tagline:'J.A.R.V.I.S. AI autonomous desktop agent',
    summary:'Autonomous AI desktop agent for Windows. Uses local LLMs (Ollama), A* UI navigation, DAG memory model, Telegram remote control, and self-learning macros.',
    highlights:['LLM-powered intent recognition (Ollama)','A* pathfinding for UI state navigation','5-layer DAG persistent memory model','Telegram bot remote command interface'],
    tech:['Python','Ollama','LLM'],
    github:'https://github.com/thippeswammy/JarvisControlSystem', isPrivate:false },

  { id:'parking', cluster:'apps', name:'SmartCarParkingSystem', lang:'Java',
    tagline:'Real-time smart parking Android app',
    summary:'Android smart parking app with Firebase Firestore real-time updates, Google Maps navigation, IoT sensor integration, and payment gateway.',
    highlights:['Firebase Firestore real-time slot updates','Google Maps navigation integration','Razorpay/Stripe payment gateway','IoT sensor + AI camera slot detection'],
    tech:['Android','Java','Firebase','Google Maps'],
    github:'https://github.com/thippeswammy/SmartParking', isPrivate:true },

  { id:'speech', cluster:'apps', name:'SpeechCalculator', lang:'Java',
    tagline:'Voice-enabled math calculator for Android',
    summary:'Android calculator using speech recognition to parse spoken math expressions with a custom priority-based expression evaluator and voice feedback.',
    highlights:['Android SpeechRecognizer API integration','Custom expression tokenizer & parser','Operator precedence evaluation engine','Voice feedback for calculation results'],
    tech:['Java','Android'],
    github:'https://github.com/thippeswammy/SpeechCalculator', isPrivate:false },

  { id:'roadtag', cluster:'apps', name:'RoadTagByCameraGps', lang:'Kotlin',
    tagline:'GPS-tagged road imagery collection',
    summary:'Android app for collecting GPS-tagged road imagery, synchronizing camera and GPS data for road annotation and mapping workflows.',
    highlights:['Synchronized camera + GPS capture','Geotagged image metadata embedding','Background location tracking service','CSV/JSON export for mapping tools'],
    tech:['Kotlin','Android'],
    github:'https://github.com/thippeswammy/RoadTagByCameraGps', isPrivate:true },

  { id:'loginadv', cluster:'apps', name:'LoginSystemWithAdvanceGUI', lang:'Java',
    tagline:'Advanced Java authentication system',
    summary:'Java Swing authentication system with structured login/registration workflows, modular GUI design, real-time input validation, and event-driven architecture.',
    highlights:['Modular login/registration workflow','Real-time input validation feedback','Event-driven programming pattern','Scalable desktop GUI architecture'],
    tech:['Java','Swing'],
    github:'https://github.com/thippeswammy/LoginSystemWithAdvanceGUI', isPrivate:false },

  // ── DEV TOOLS & RESEARCH ────────────────────────────────────────────────────
  { id:'rosrec', cluster:'tools', name:'ROSDataRecorder', lang:'Python',
    tagline:'ROS multi-sensor data recording & comparison',
    summary:'Synchronized ROS sensor data recording tool with playback and comparison analysis for validating SLAM, odometry, and perception pipelines.',
    highlights:['Multi-sensor synchronized recording','Rosbag playback & comparison tools','Trajectory & sensor data overlay','Automated quality metric reporting'],
    tech:['Python','ROS','ROS 2'],
    github:'https://github.com/thippeswammy/ROSDataRecorderandComparisonWalkthrough', isPrivate:true },

  { id:'dataviz', cluster:'tools', name:'DataVisualizationEditingTool', lang:'Python',
    tagline:'Interactive sensor data visualization editor',
    summary:'Custom Python tool for editing, annotating, and visualizing sensor data and trajectory datasets with interactive plotting and export capabilities.',
    highlights:['Interactive plot annotation & editing','Multi-dataset overlay visualization','Custom color mapping & filtering','CSV/NumPy data export pipeline'],
    tech:['Python','Matplotlib','NumPy'],
    github:'https://github.com/thippeswammy/DataVisualizationEditingTool', isPrivate:true },

  { id:'lidar', cluster:'tools', name:'LidarScanSegment', lang:'Python',
    tagline:'LiDAR point cloud scan segmentation',
    summary:'Python LiDAR scan segmentation tool for autonomous vehicle perception — ground removal, Euclidean cluster extraction, and label export.',
    highlights:['Ground plane removal (RANSAC)','Euclidean cluster extraction','Scan-level label assignment','ROS bag & PCL file input support'],
    tech:['Python','PCL','ROS'],
    github:'https://github.com/thippeswammy/LidarScanSegment', isPrivate:true },

  { id:'mcp', cluster:'tools', name:'my_mcp_project', lang:'Python',
    tagline:'Model Context Protocol (MCP) tooling',
    summary:'MCP server implementation for integrating local tools and resources with LLM backends for AI agent workflows with extensible plugin architecture.',
    highlights:['MCP server implementation','Tool & resource provider integration','LLM context management pipeline','Extensible plugin architecture'],
    tech:['Python','MCP'],
    github:'https://github.com/thippeswammy/my_mcp_project', isPrivate:false },

  { id:'neetcode', cluster:'tools', name:'NeetCodeProblems', lang:'Java',
    tagline:'NeetCode 150 algorithm solutions in Java',
    summary:'Java solutions to NeetCode 150 roadmap problems — arrays, graphs, DP, trees, and system design — structured for interview preparation.',
    highlights:['NeetCode 150 roadmap coverage','Graph, DP & tree algorithm solutions','Time/space complexity documentation','Clean OOP Java implementation style'],
    tech:['Java'],
    github:'https://github.com/thippeswammy/NeetCodeProblems', isPrivate:false },
];
