  {
    id: 'jarviscontrolsystem',
    cluster: 'software',
    name: 'JarvisControlSystem',
    lang: 'Python',
    tagline: 'An advanced, autonomous virtual assistant and desktop agent',
    summary: 'An advanced, autonomous virtual assistant system inspired by J.A.R.V.I.S from Iron Man. It is a self-aware, state-persistent, and fully autonomous desktop agent built on the robust v2.1 "Iron Man" Architecture. It provides seamless, hands-free automation of the digital workspace by decoupling cognitive intent from physical execution.',
    highlights: [
      'Orchestrator brain and continuous Verification Loop',
      'Powered by local LLMs (like Ollama/gemma3)',
      'State-Aware Delta Navigation (Look-Before-You-Leap execution)',
      'Self-Learning Semantic Macros stored in a Graph DB',
      '5-layer persistent memory model with a RAG context pipeline',
      'Telegram bot integration for remote control'
    ],
    tech: ['Python', 'LLM', 'Ollama', 'RAG', 'Graph DB', 'Telegram API'],
    github: 'https://github.com/thippeswammy/JarvisControlSystem',
    demo: '',
    docs: '',
    paper: '',
    isPrivate: false,
    status: 'ongoing',
    year: '',
    team: 'solo',
    platform: ['Windows'],
    datasets: [],
    thumbnail: '',
    images: [],
    metrics: {}
  }
